// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package event_subscription

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}
	compareTags(delta, a, b)

	if ackcompare.HasNilDifference(a.ko.Spec.Enabled, b.ko.Spec.Enabled) {
		delta.Add("Spec.Enabled", a.ko.Spec.Enabled, b.ko.Spec.Enabled)
	} else if a.ko.Spec.Enabled != nil && b.ko.Spec.Enabled != nil {
		if *a.ko.Spec.Enabled != *b.ko.Spec.Enabled {
			delta.Add("Spec.Enabled", a.ko.Spec.Enabled, b.ko.Spec.Enabled)
		}
	}
	if len(a.ko.Spec.EventCategories) != len(b.ko.Spec.EventCategories) {
		delta.Add("Spec.EventCategories", a.ko.Spec.EventCategories, b.ko.Spec.EventCategories)
	} else if len(a.ko.Spec.EventCategories) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.EventCategories, b.ko.Spec.EventCategories) {
			delta.Add("Spec.EventCategories", a.ko.Spec.EventCategories, b.ko.Spec.EventCategories)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SNSTopicARN, b.ko.Spec.SNSTopicARN) {
		delta.Add("Spec.SNSTopicARN", a.ko.Spec.SNSTopicARN, b.ko.Spec.SNSTopicARN)
	} else if a.ko.Spec.SNSTopicARN != nil && b.ko.Spec.SNSTopicARN != nil {
		if *a.ko.Spec.SNSTopicARN != *b.ko.Spec.SNSTopicARN {
			delta.Add("Spec.SNSTopicARN", a.ko.Spec.SNSTopicARN, b.ko.Spec.SNSTopicARN)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.SNSTopicRef, b.ko.Spec.SNSTopicRef) {
		delta.Add("Spec.SNSTopicRef", a.ko.Spec.SNSTopicRef, b.ko.Spec.SNSTopicRef)
	}
	if len(a.ko.Spec.SourceIDs) != len(b.ko.Spec.SourceIDs) {
		delta.Add("Spec.SourceIDs", a.ko.Spec.SourceIDs, b.ko.Spec.SourceIDs)
	} else if len(a.ko.Spec.SourceIDs) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.SourceIDs, b.ko.Spec.SourceIDs) {
			delta.Add("Spec.SourceIDs", a.ko.Spec.SourceIDs, b.ko.Spec.SourceIDs)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SourceType, b.ko.Spec.SourceType) {
		delta.Add("Spec.SourceType", a.ko.Spec.SourceType, b.ko.Spec.SourceType)
	} else if a.ko.Spec.SourceType != nil && b.ko.Spec.SourceType != nil {
		if *a.ko.Spec.SourceType != *b.ko.Spec.SourceType {
			delta.Add("Spec.SourceType", a.ko.Spec.SourceType, b.ko.Spec.SourceType)
		}
	}

	return delta
}
