// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package event_subscription

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"
	"time"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/databasemigrationservice"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/databasemigrationservice/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/dms-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.EventSubscription{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DescribeEventSubscriptionsOutput
	resp, err = rm.sdkapi.DescribeEventSubscriptions(ctx, input)

	// sdk_read_many_post_request hook
	//
	// Map ResourceNotFoundFault to NotFound error so ACK can trigger createResource
	// correctly.
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundFault" {
			rm.metrics.RecordAPICall("READ_MANY", "DescribeEventSubscriptions", err)
			return nil, ackerr.NotFound
		}
	}

	rm.metrics.RecordAPICall("READ_MANY", "DescribeEventSubscriptions", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.EventSubscriptionsList {
		if elem.CustSubscriptionId != nil {
			ko.Spec.Name = elem.CustSubscriptionId
		} else {
			ko.Spec.Name = nil
		}
		ko.Spec.Enabled = &elem.Enabled
		if elem.EventCategoriesList != nil {
			ko.Spec.EventCategories = aws.StringSlice(elem.EventCategoriesList)
		} else {
			ko.Spec.EventCategories = nil
		}
		if elem.SnsTopicArn != nil {
			ko.Spec.SNSTopicARN = elem.SnsTopicArn
		} else {
			ko.Spec.SNSTopicARN = nil
		}
		if elem.SourceIdsList != nil {
			ko.Spec.SourceIDs = aws.StringSlice(elem.SourceIdsList)
		} else {
			ko.Spec.SourceIDs = nil
		}
		if elem.SourceType != nil {
			ko.Spec.SourceType = elem.SourceType
		} else {
			ko.Spec.SourceType = nil
		}
		if elem.Status != nil {
			ko.Status.SubscriptionStatus = elem.Status
		} else {
			ko.Status.SubscriptionStatus = nil
		}
		if elem.SubscriptionCreationTime != nil {
			ko.Status.SubscriptionCreationTime = elem.SubscriptionCreationTime
		} else {
			ko.Status.SubscriptionCreationTime = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)

	// sdk_read_many_post_set_output hook
	//
	// The API does not return the ARN so we build it ourselves.
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.ARN == nil {
		arn := ackv1alpha1.AWSResourceName(fmt.Sprintf(
			"arn:%s:dms:%s:%s:es:%s",
			partitionFromRegion(string(rm.awsRegion)),
			rm.awsRegion,
			rm.awsAccountID,
			*ko.Spec.Name,
		))
		ko.Status.ACKResourceMetadata.ARN = &arn
	}

	// sdk_read_many_post_set_output hook
	//
	// Retrieves the latest tags
	if ko.Status.ACKResourceMetadata != nil && ko.Status.ACKResourceMetadata.ARN != nil {
		resourceARN := (*string)(ko.Status.ACKResourceMetadata.ARN)
		tags, err := rm.getTags(ctx, *resourceARN)
		if err != nil {
			return nil, err
		}
		ko.Spec.Tags = tags
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return r.ko.Spec.Name == nil

}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeEventSubscriptionsInput, error) {
	res := &svcsdk.DescribeEventSubscriptionsInput{}

	if r.ko.Spec.Name != nil {
		res.SubscriptionName = r.ko.Spec.Name
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateEventSubscriptionOutput
	_ = resp
	resp, err = rm.sdkapi.CreateEventSubscription(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateEventSubscription", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.EventSubscription.CustSubscriptionId != nil {
		ko.Spec.Name = resp.EventSubscription.CustSubscriptionId
	} else {
		ko.Spec.Name = nil
	}
	if resp.EventSubscription.CustomerAwsId != nil {
		ko.Status.CustomerAccountID = resp.EventSubscription.CustomerAwsId
	} else {
		ko.Status.CustomerAccountID = nil
	}
	ko.Spec.Enabled = &resp.EventSubscription.Enabled
	if resp.EventSubscription.EventCategoriesList != nil {
		ko.Spec.EventCategories = aws.StringSlice(resp.EventSubscription.EventCategoriesList)
	} else {
		ko.Spec.EventCategories = nil
	}
	if resp.EventSubscription.SnsTopicArn != nil {
		ko.Spec.SNSTopicARN = resp.EventSubscription.SnsTopicArn
	} else {
		ko.Spec.SNSTopicARN = nil
	}
	if resp.EventSubscription.SourceIdsList != nil {
		ko.Spec.SourceIDs = aws.StringSlice(resp.EventSubscription.SourceIdsList)
	} else {
		ko.Spec.SourceIDs = nil
	}
	if resp.EventSubscription.SourceType != nil {
		ko.Spec.SourceType = resp.EventSubscription.SourceType
	} else {
		ko.Spec.SourceType = nil
	}
	if resp.EventSubscription.Status != nil {
		ko.Status.SubscriptionStatus = resp.EventSubscription.Status
	} else {
		ko.Status.SubscriptionStatus = nil
	}
	if resp.EventSubscription.SubscriptionCreationTime != nil {
		ko.Status.SubscriptionCreationTime = resp.EventSubscription.SubscriptionCreationTime
	} else {
		ko.Status.SubscriptionCreationTime = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateEventSubscriptionInput, error) {
	res := &svcsdk.CreateEventSubscriptionInput{}

	if r.ko.Spec.Enabled != nil {
		res.Enabled = r.ko.Spec.Enabled
	}
	if r.ko.Spec.EventCategories != nil {
		res.EventCategories = aws.ToStringSlice(r.ko.Spec.EventCategories)
	}
	if r.ko.Spec.SNSTopicARN != nil {
		res.SnsTopicArn = r.ko.Spec.SNSTopicARN
	}
	if r.ko.Spec.SourceIDs != nil {
		res.SourceIds = aws.ToStringSlice(r.ko.Spec.SourceIDs)
	}
	if r.ko.Spec.SourceType != nil {
		res.SourceType = r.ko.Spec.SourceType
	}
	if r.ko.Spec.Name != nil {
		res.SubscriptionName = r.ko.Spec.Name
	}
	if r.ko.Spec.Tags != nil {
		f6 := []svcsdktypes.Tag{}
		for _, f6iter := range r.ko.Spec.Tags {
			f6elem := &svcsdktypes.Tag{}
			if f6iter.Key != nil {
				f6elem.Key = f6iter.Key
			}
			if f6iter.ResourceARN != nil {
				f6elem.ResourceArn = f6iter.ResourceARN
			}
			if f6iter.Value != nil {
				f6elem.Value = f6iter.Value
			}
			f6 = append(f6, *f6elem)
		}
		res.Tags = f6
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.ModifyEventSubscriptionOutput
	_ = resp
	resp, err = rm.sdkapi.ModifyEventSubscription(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "ModifyEventSubscription", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	// sdk_update_pre_set_output hook
	if delta.DifferentAt("Spec.Tags") {
		if err = rm.syncTags(ctx, desired, latest); err != nil {
			return nil, err
		}
	}

	if resp.EventSubscription.CustSubscriptionId != nil {
		ko.Spec.Name = resp.EventSubscription.CustSubscriptionId
	} else {
		ko.Spec.Name = nil
	}
	if resp.EventSubscription.CustomerAwsId != nil {
		ko.Status.CustomerAccountID = resp.EventSubscription.CustomerAwsId
	} else {
		ko.Status.CustomerAccountID = nil
	}
	ko.Spec.Enabled = &resp.EventSubscription.Enabled
	if resp.EventSubscription.EventCategoriesList != nil {
		ko.Spec.EventCategories = aws.StringSlice(resp.EventSubscription.EventCategoriesList)
	} else {
		ko.Spec.EventCategories = nil
	}
	if resp.EventSubscription.SnsTopicArn != nil {
		ko.Spec.SNSTopicARN = resp.EventSubscription.SnsTopicArn
	} else {
		ko.Spec.SNSTopicARN = nil
	}
	if resp.EventSubscription.SourceIdsList != nil {
		ko.Spec.SourceIDs = aws.StringSlice(resp.EventSubscription.SourceIdsList)
	} else {
		ko.Spec.SourceIDs = nil
	}
	if resp.EventSubscription.SourceType != nil {
		ko.Spec.SourceType = resp.EventSubscription.SourceType
	} else {
		ko.Spec.SourceType = nil
	}
	if resp.EventSubscription.Status != nil {
		ko.Status.SubscriptionStatus = resp.EventSubscription.Status
	} else {
		ko.Status.SubscriptionStatus = nil
	}
	if resp.EventSubscription.SubscriptionCreationTime != nil {
		ko.Status.SubscriptionCreationTime = resp.EventSubscription.SubscriptionCreationTime
	} else {
		ko.Status.SubscriptionCreationTime = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.ModifyEventSubscriptionInput, error) {
	res := &svcsdk.ModifyEventSubscriptionInput{}

	if r.ko.Spec.Enabled != nil {
		res.Enabled = r.ko.Spec.Enabled
	}
	if r.ko.Spec.EventCategories != nil {
		res.EventCategories = aws.ToStringSlice(r.ko.Spec.EventCategories)
	}
	if r.ko.Spec.SNSTopicARN != nil {
		res.SnsTopicArn = r.ko.Spec.SNSTopicARN
	}
	if r.ko.Spec.SourceType != nil {
		res.SourceType = r.ko.Spec.SourceType
	}
	if r.ko.Spec.Name != nil {
		res.SubscriptionName = r.ko.Spec.Name
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteEventSubscriptionOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteEventSubscription(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteEventSubscription", err)

	// sdk_delete_post_request hook
	//
	// Wait for the event subscription to be deleted before setResourceUnmanaged.
	if err != nil {
		return nil, err
	}
	r.ko.Status.SubscriptionStatus = aws.String(eventSubscriptionStatusDeleting)
	return r, ackrequeue.NeededAfter(
		errors.New(fmt.Sprintf("EventSubscription is in %v state", *r.ko.Status.SubscriptionStatus)),
		10*time.Second)

	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteEventSubscriptionInput, error) {
	res := &svcsdk.DeleteEventSubscriptionInput{}

	if r.ko.Spec.Name != nil {
		res.SubscriptionName = r.ko.Spec.Name
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.EventSubscription,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
