// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package replication_instance

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}
	compareTags(delta, a, b)

	if ackcompare.HasNilDifference(a.ko.Spec.AllocatedStorage, b.ko.Spec.AllocatedStorage) {
		delta.Add("Spec.AllocatedStorage", a.ko.Spec.AllocatedStorage, b.ko.Spec.AllocatedStorage)
	} else if a.ko.Spec.AllocatedStorage != nil && b.ko.Spec.AllocatedStorage != nil {
		if *a.ko.Spec.AllocatedStorage != *b.ko.Spec.AllocatedStorage {
			delta.Add("Spec.AllocatedStorage", a.ko.Spec.AllocatedStorage, b.ko.Spec.AllocatedStorage)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.AutoMinorVersionUpgrade, b.ko.Spec.AutoMinorVersionUpgrade) {
		delta.Add("Spec.AutoMinorVersionUpgrade", a.ko.Spec.AutoMinorVersionUpgrade, b.ko.Spec.AutoMinorVersionUpgrade)
	} else if a.ko.Spec.AutoMinorVersionUpgrade != nil && b.ko.Spec.AutoMinorVersionUpgrade != nil {
		if *a.ko.Spec.AutoMinorVersionUpgrade != *b.ko.Spec.AutoMinorVersionUpgrade {
			delta.Add("Spec.AutoMinorVersionUpgrade", a.ko.Spec.AutoMinorVersionUpgrade, b.ko.Spec.AutoMinorVersionUpgrade)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.AvailabilityZone, b.ko.Spec.AvailabilityZone) {
		delta.Add("Spec.AvailabilityZone", a.ko.Spec.AvailabilityZone, b.ko.Spec.AvailabilityZone)
	} else if a.ko.Spec.AvailabilityZone != nil && b.ko.Spec.AvailabilityZone != nil {
		if *a.ko.Spec.AvailabilityZone != *b.ko.Spec.AvailabilityZone {
			delta.Add("Spec.AvailabilityZone", a.ko.Spec.AvailabilityZone, b.ko.Spec.AvailabilityZone)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DNSNameServers, b.ko.Spec.DNSNameServers) {
		delta.Add("Spec.DNSNameServers", a.ko.Spec.DNSNameServers, b.ko.Spec.DNSNameServers)
	} else if a.ko.Spec.DNSNameServers != nil && b.ko.Spec.DNSNameServers != nil {
		if *a.ko.Spec.DNSNameServers != *b.ko.Spec.DNSNameServers {
			delta.Add("Spec.DNSNameServers", a.ko.Spec.DNSNameServers, b.ko.Spec.DNSNameServers)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.EngineVersion, b.ko.Spec.EngineVersion) {
		delta.Add("Spec.EngineVersion", a.ko.Spec.EngineVersion, b.ko.Spec.EngineVersion)
	} else if a.ko.Spec.EngineVersion != nil && b.ko.Spec.EngineVersion != nil {
		if *a.ko.Spec.EngineVersion != *b.ko.Spec.EngineVersion {
			delta.Add("Spec.EngineVersion", a.ko.Spec.EngineVersion, b.ko.Spec.EngineVersion)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.InstanceClass, b.ko.Spec.InstanceClass) {
		delta.Add("Spec.InstanceClass", a.ko.Spec.InstanceClass, b.ko.Spec.InstanceClass)
	} else if a.ko.Spec.InstanceClass != nil && b.ko.Spec.InstanceClass != nil {
		if *a.ko.Spec.InstanceClass != *b.ko.Spec.InstanceClass {
			delta.Add("Spec.InstanceClass", a.ko.Spec.InstanceClass, b.ko.Spec.InstanceClass)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.KerberosAuthenticationSettings, b.ko.Spec.KerberosAuthenticationSettings) {
		delta.Add("Spec.KerberosAuthenticationSettings", a.ko.Spec.KerberosAuthenticationSettings, b.ko.Spec.KerberosAuthenticationSettings)
	} else if a.ko.Spec.KerberosAuthenticationSettings != nil && b.ko.Spec.KerberosAuthenticationSettings != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretIAMARN, b.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretIAMARN) {
			delta.Add("Spec.KerberosAuthenticationSettings.KeyCacheSecretIAMARN", a.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretIAMARN, b.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretIAMARN)
		} else if a.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretIAMARN != nil && b.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretIAMARN != nil {
			if *a.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretIAMARN != *b.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretIAMARN {
				delta.Add("Spec.KerberosAuthenticationSettings.KeyCacheSecretIAMARN", a.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretIAMARN, b.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretIAMARN)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretID, b.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretID) {
			delta.Add("Spec.KerberosAuthenticationSettings.KeyCacheSecretID", a.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretID, b.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretID)
		} else if a.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretID != nil && b.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretID != nil {
			if *a.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretID != *b.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretID {
				delta.Add("Spec.KerberosAuthenticationSettings.KeyCacheSecretID", a.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretID, b.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretID)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.KerberosAuthenticationSettings.Krb5FileContents, b.ko.Spec.KerberosAuthenticationSettings.Krb5FileContents) {
			delta.Add("Spec.KerberosAuthenticationSettings.Krb5FileContents", a.ko.Spec.KerberosAuthenticationSettings.Krb5FileContents, b.ko.Spec.KerberosAuthenticationSettings.Krb5FileContents)
		} else if a.ko.Spec.KerberosAuthenticationSettings.Krb5FileContents != nil && b.ko.Spec.KerberosAuthenticationSettings.Krb5FileContents != nil {
			if *a.ko.Spec.KerberosAuthenticationSettings.Krb5FileContents != *b.ko.Spec.KerberosAuthenticationSettings.Krb5FileContents {
				delta.Add("Spec.KerberosAuthenticationSettings.Krb5FileContents", a.ko.Spec.KerberosAuthenticationSettings.Krb5FileContents, b.ko.Spec.KerberosAuthenticationSettings.Krb5FileContents)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.KMSKeyID, b.ko.Spec.KMSKeyID) {
		delta.Add("Spec.KMSKeyID", a.ko.Spec.KMSKeyID, b.ko.Spec.KMSKeyID)
	} else if a.ko.Spec.KMSKeyID != nil && b.ko.Spec.KMSKeyID != nil {
		if *a.ko.Spec.KMSKeyID != *b.ko.Spec.KMSKeyID {
			delta.Add("Spec.KMSKeyID", a.ko.Spec.KMSKeyID, b.ko.Spec.KMSKeyID)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.KMSKeyRef, b.ko.Spec.KMSKeyRef) {
		delta.Add("Spec.KMSKeyRef", a.ko.Spec.KMSKeyRef, b.ko.Spec.KMSKeyRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MultiAZ, b.ko.Spec.MultiAZ) {
		delta.Add("Spec.MultiAZ", a.ko.Spec.MultiAZ, b.ko.Spec.MultiAZ)
	} else if a.ko.Spec.MultiAZ != nil && b.ko.Spec.MultiAZ != nil {
		if *a.ko.Spec.MultiAZ != *b.ko.Spec.MultiAZ {
			delta.Add("Spec.MultiAZ", a.ko.Spec.MultiAZ, b.ko.Spec.MultiAZ)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.NetworkType, b.ko.Spec.NetworkType) {
		delta.Add("Spec.NetworkType", a.ko.Spec.NetworkType, b.ko.Spec.NetworkType)
	} else if a.ko.Spec.NetworkType != nil && b.ko.Spec.NetworkType != nil {
		if *a.ko.Spec.NetworkType != *b.ko.Spec.NetworkType {
			delta.Add("Spec.NetworkType", a.ko.Spec.NetworkType, b.ko.Spec.NetworkType)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.PreferredMaintenanceWindow, b.ko.Spec.PreferredMaintenanceWindow) {
		delta.Add("Spec.PreferredMaintenanceWindow", a.ko.Spec.PreferredMaintenanceWindow, b.ko.Spec.PreferredMaintenanceWindow)
	} else if a.ko.Spec.PreferredMaintenanceWindow != nil && b.ko.Spec.PreferredMaintenanceWindow != nil {
		if *a.ko.Spec.PreferredMaintenanceWindow != *b.ko.Spec.PreferredMaintenanceWindow {
			delta.Add("Spec.PreferredMaintenanceWindow", a.ko.Spec.PreferredMaintenanceWindow, b.ko.Spec.PreferredMaintenanceWindow)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.PubliclyAccessible, b.ko.Spec.PubliclyAccessible) {
		delta.Add("Spec.PubliclyAccessible", a.ko.Spec.PubliclyAccessible, b.ko.Spec.PubliclyAccessible)
	} else if a.ko.Spec.PubliclyAccessible != nil && b.ko.Spec.PubliclyAccessible != nil {
		if *a.ko.Spec.PubliclyAccessible != *b.ko.Spec.PubliclyAccessible {
			delta.Add("Spec.PubliclyAccessible", a.ko.Spec.PubliclyAccessible, b.ko.Spec.PubliclyAccessible)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ResourceIdentifier, b.ko.Spec.ResourceIdentifier) {
		delta.Add("Spec.ResourceIdentifier", a.ko.Spec.ResourceIdentifier, b.ko.Spec.ResourceIdentifier)
	} else if a.ko.Spec.ResourceIdentifier != nil && b.ko.Spec.ResourceIdentifier != nil {
		if *a.ko.Spec.ResourceIdentifier != *b.ko.Spec.ResourceIdentifier {
			delta.Add("Spec.ResourceIdentifier", a.ko.Spec.ResourceIdentifier, b.ko.Spec.ResourceIdentifier)
		}
	}
	if len(a.ko.Spec.SecurityGroupIDs) != len(b.ko.Spec.SecurityGroupIDs) {
		delta.Add("Spec.SecurityGroupIDs", a.ko.Spec.SecurityGroupIDs, b.ko.Spec.SecurityGroupIDs)
	} else if len(a.ko.Spec.SecurityGroupIDs) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.SecurityGroupIDs, b.ko.Spec.SecurityGroupIDs) {
			delta.Add("Spec.SecurityGroupIDs", a.ko.Spec.SecurityGroupIDs, b.ko.Spec.SecurityGroupIDs)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.SecurityGroupRefs, b.ko.Spec.SecurityGroupRefs) {
		delta.Add("Spec.SecurityGroupRefs", a.ko.Spec.SecurityGroupRefs, b.ko.Spec.SecurityGroupRefs)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SubnetGroupID, b.ko.Spec.SubnetGroupID) {
		delta.Add("Spec.SubnetGroupID", a.ko.Spec.SubnetGroupID, b.ko.Spec.SubnetGroupID)
	} else if a.ko.Spec.SubnetGroupID != nil && b.ko.Spec.SubnetGroupID != nil {
		if *a.ko.Spec.SubnetGroupID != *b.ko.Spec.SubnetGroupID {
			delta.Add("Spec.SubnetGroupID", a.ko.Spec.SubnetGroupID, b.ko.Spec.SubnetGroupID)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.SubnetGroupRef, b.ko.Spec.SubnetGroupRef) {
		delta.Add("Spec.SubnetGroupRef", a.ko.Spec.SubnetGroupRef, b.ko.Spec.SubnetGroupRef)
	}

	return delta
}
