// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package replication_instance

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"
	"time"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/databasemigrationservice"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/databasemigrationservice/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/dms-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.ReplicationInstance{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}

	// sdk_read_many_post_build_request hook
	//
	// DescribeReplicationInstances does not provide any identifier input fields,
	// so we need to build a filter on our own.
	input.Filters = []svcsdktypes.Filter{
		{
			Name:   aws.String("replication-instance-id"),
			Values: []string{aws.ToString(r.ko.Spec.Name)},
		},
	}

	var resp *svcsdk.DescribeReplicationInstancesOutput
	resp, err = rm.sdkapi.DescribeReplicationInstances(ctx, input)

	// sdk_read_many_post_request hook
	//
	// Map ResourceNotFoundFault to NotFound error so ACK can trigger createResource
	// correctly.
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundFault" {
			rm.metrics.RecordAPICall("READ_MANY", "DescribeReplicationInstances", err)
			return nil, ackerr.NotFound
		}
	}

	rm.metrics.RecordAPICall("READ_MANY", "DescribeReplicationInstances", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.ReplicationInstances {
		allocatedStorageCopy := int64(elem.AllocatedStorage)
		ko.Spec.AllocatedStorage = &allocatedStorageCopy
		ko.Spec.AutoMinorVersionUpgrade = &elem.AutoMinorVersionUpgrade
		if elem.AvailabilityZone != nil {
			ko.Spec.AvailabilityZone = elem.AvailabilityZone
		} else {
			ko.Spec.AvailabilityZone = nil
		}
		if elem.DnsNameServers != nil {
			ko.Spec.DNSNameServers = elem.DnsNameServers
		} else {
			ko.Spec.DNSNameServers = nil
		}
		if elem.EngineVersion != nil {
			ko.Spec.EngineVersion = elem.EngineVersion
		} else {
			ko.Spec.EngineVersion = nil
		}
		if elem.FreeUntil != nil {
			ko.Status.FreeUntil = &metav1.Time{*elem.FreeUntil}
		} else {
			ko.Status.FreeUntil = nil
		}
		if elem.InstanceCreateTime != nil {
			ko.Status.InstanceCreateTime = &metav1.Time{*elem.InstanceCreateTime}
		} else {
			ko.Status.InstanceCreateTime = nil
		}
		if elem.KerberosAuthenticationSettings != nil {
			f7 := &svcapitypes.KerberosAuthenticationSettings{}
			if elem.KerberosAuthenticationSettings.KeyCacheSecretIamArn != nil {
				f7.KeyCacheSecretIAMARN = elem.KerberosAuthenticationSettings.KeyCacheSecretIamArn
			}
			if elem.KerberosAuthenticationSettings.KeyCacheSecretId != nil {
				f7.KeyCacheSecretID = elem.KerberosAuthenticationSettings.KeyCacheSecretId
			}
			if elem.KerberosAuthenticationSettings.Krb5FileContents != nil {
				f7.Krb5FileContents = elem.KerberosAuthenticationSettings.Krb5FileContents
			}
			ko.Spec.KerberosAuthenticationSettings = f7
		} else {
			ko.Spec.KerberosAuthenticationSettings = nil
		}
		if elem.KmsKeyId != nil {
			ko.Spec.KMSKeyID = elem.KmsKeyId
		} else {
			ko.Spec.KMSKeyID = nil
		}
		ko.Spec.MultiAZ = &elem.MultiAZ
		if elem.NetworkType != nil {
			ko.Spec.NetworkType = elem.NetworkType
		} else {
			ko.Spec.NetworkType = nil
		}
		if elem.PendingModifiedValues != nil {
			f11 := &svcapitypes.ReplicationPendingModifiedValues{}
			if elem.PendingModifiedValues.AllocatedStorage != nil {
				allocatedStorageCopy := int64(*elem.PendingModifiedValues.AllocatedStorage)
				f11.AllocatedStorage = &allocatedStorageCopy
			}
			if elem.PendingModifiedValues.EngineVersion != nil {
				f11.EngineVersion = elem.PendingModifiedValues.EngineVersion
			}
			if elem.PendingModifiedValues.MultiAZ != nil {
				f11.MultiAZ = elem.PendingModifiedValues.MultiAZ
			}
			if elem.PendingModifiedValues.NetworkType != nil {
				f11.NetworkType = elem.PendingModifiedValues.NetworkType
			}
			if elem.PendingModifiedValues.ReplicationInstanceClass != nil {
				f11.ReplicationInstanceClass = elem.PendingModifiedValues.ReplicationInstanceClass
			}
			ko.Status.PendingModifiedValues = f11
		} else {
			ko.Status.PendingModifiedValues = nil
		}
		if elem.PreferredMaintenanceWindow != nil {
			ko.Spec.PreferredMaintenanceWindow = elem.PreferredMaintenanceWindow
		} else {
			ko.Spec.PreferredMaintenanceWindow = nil
		}
		ko.Spec.PubliclyAccessible = &elem.PubliclyAccessible
		if elem.ReplicationInstanceArn != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.ReplicationInstanceArn)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.ReplicationInstanceClass != nil {
			ko.Spec.InstanceClass = elem.ReplicationInstanceClass
		} else {
			ko.Spec.InstanceClass = nil
		}
		if elem.ReplicationInstanceIdentifier != nil {
			ko.Spec.Name = elem.ReplicationInstanceIdentifier
		} else {
			ko.Spec.Name = nil
		}
		if elem.ReplicationInstanceIpv6Addresses != nil {
			ko.Status.ReplicationInstanceIPv6Addresses = aws.StringSlice(elem.ReplicationInstanceIpv6Addresses)
		} else {
			ko.Status.ReplicationInstanceIPv6Addresses = nil
		}
		if elem.ReplicationInstancePrivateIpAddress != nil {
			ko.Status.ReplicationInstancePrivateIPAddress = elem.ReplicationInstancePrivateIpAddress
		} else {
			ko.Status.ReplicationInstancePrivateIPAddress = nil
		}
		if elem.ReplicationInstancePrivateIpAddresses != nil {
			ko.Status.ReplicationInstancePrivateIPAddresses = aws.StringSlice(elem.ReplicationInstancePrivateIpAddresses)
		} else {
			ko.Status.ReplicationInstancePrivateIPAddresses = nil
		}
		if elem.ReplicationInstancePublicIpAddress != nil {
			ko.Status.ReplicationInstancePublicIPAddress = elem.ReplicationInstancePublicIpAddress
		} else {
			ko.Status.ReplicationInstancePublicIPAddress = nil
		}
		if elem.ReplicationInstancePublicIpAddresses != nil {
			ko.Status.ReplicationInstancePublicIPAddresses = aws.StringSlice(elem.ReplicationInstancePublicIpAddresses)
		} else {
			ko.Status.ReplicationInstancePublicIPAddresses = nil
		}
		if elem.ReplicationInstanceStatus != nil {
			ko.Status.ReplicationInstanceStatus = elem.ReplicationInstanceStatus
		} else {
			ko.Status.ReplicationInstanceStatus = nil
		}
		if elem.ReplicationSubnetGroup != nil {
			f23 := &svcapitypes.ReplicationSubnetGroup_SDK{}
			if elem.ReplicationSubnetGroup.IsReadOnly != nil {
				f23.IsReadOnly = elem.ReplicationSubnetGroup.IsReadOnly
			}
			if elem.ReplicationSubnetGroup.ReplicationSubnetGroupDescription != nil {
				f23.ReplicationSubnetGroupDescription = elem.ReplicationSubnetGroup.ReplicationSubnetGroupDescription
			}
			if elem.ReplicationSubnetGroup.ReplicationSubnetGroupIdentifier != nil {
				f23.ReplicationSubnetGroupIdentifier = elem.ReplicationSubnetGroup.ReplicationSubnetGroupIdentifier
			}
			if elem.ReplicationSubnetGroup.SubnetGroupStatus != nil {
				f23.SubnetGroupStatus = elem.ReplicationSubnetGroup.SubnetGroupStatus
			}
			if elem.ReplicationSubnetGroup.Subnets != nil {
				f23f4 := []*svcapitypes.Subnet{}
				for _, f23f4iter := range elem.ReplicationSubnetGroup.Subnets {
					f23f4elem := &svcapitypes.Subnet{}
					if f23f4iter.SubnetAvailabilityZone != nil {
						f23f4elemf0 := &svcapitypes.AvailabilityZone{}
						if f23f4iter.SubnetAvailabilityZone.Name != nil {
							f23f4elemf0.Name = f23f4iter.SubnetAvailabilityZone.Name
						}
						f23f4elem.SubnetAvailabilityZone = f23f4elemf0
					}
					if f23f4iter.SubnetIdentifier != nil {
						f23f4elem.SubnetIdentifier = f23f4iter.SubnetIdentifier
					}
					if f23f4iter.SubnetStatus != nil {
						f23f4elem.SubnetStatus = f23f4iter.SubnetStatus
					}
					f23f4 = append(f23f4, f23f4elem)
				}
				f23.Subnets = f23f4
			}
			if elem.ReplicationSubnetGroup.SupportedNetworkTypes != nil {
				f23.SupportedNetworkTypes = aws.StringSlice(elem.ReplicationSubnetGroup.SupportedNetworkTypes)
			}
			if elem.ReplicationSubnetGroup.VpcId != nil {
				f23.VPCID = elem.ReplicationSubnetGroup.VpcId
			}
			ko.Status.ReplicationSubnetGroup = f23
		} else {
			ko.Status.ReplicationSubnetGroup = nil
		}
		if elem.SecondaryAvailabilityZone != nil {
			ko.Status.SecondaryAvailabilityZone = elem.SecondaryAvailabilityZone
		} else {
			ko.Status.SecondaryAvailabilityZone = nil
		}
		if elem.VpcSecurityGroups != nil {
			f25 := []*svcapitypes.VPCSecurityGroupMembership{}
			for _, f25iter := range elem.VpcSecurityGroups {
				f25elem := &svcapitypes.VPCSecurityGroupMembership{}
				if f25iter.Status != nil {
					f25elem.Status = f25iter.Status
				}
				if f25iter.VpcSecurityGroupId != nil {
					f25elem.VPCSecurityGroupID = f25iter.VpcSecurityGroupId
				}
				f25 = append(f25, f25elem)
			}
			ko.Status.VPCSecurityGroups = f25
		} else {
			ko.Status.VPCSecurityGroups = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)

	// sdk_read_many_post_set_output hook
	//
	// Retrieves the latest tags
	if ko.Status.ACKResourceMetadata != nil && ko.Status.ACKResourceMetadata.ARN != nil {
		resourceARN := (*string)(ko.Status.ACKResourceMetadata.ARN)
		tags, err := rm.getTags(ctx, *resourceARN)
		if err != nil {
			return nil, err
		}
		ko.Spec.Tags = tags
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return false
}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeReplicationInstancesInput, error) {
	res := &svcsdk.DescribeReplicationInstancesInput{}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateReplicationInstanceOutput
	_ = resp
	resp, err = rm.sdkapi.CreateReplicationInstance(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateReplicationInstance", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	allocatedStorageCopy := int64(resp.ReplicationInstance.AllocatedStorage)
	ko.Spec.AllocatedStorage = &allocatedStorageCopy
	ko.Spec.AutoMinorVersionUpgrade = &resp.ReplicationInstance.AutoMinorVersionUpgrade
	if resp.ReplicationInstance.AvailabilityZone != nil {
		ko.Spec.AvailabilityZone = resp.ReplicationInstance.AvailabilityZone
	} else {
		ko.Spec.AvailabilityZone = nil
	}
	if resp.ReplicationInstance.DnsNameServers != nil {
		ko.Spec.DNSNameServers = resp.ReplicationInstance.DnsNameServers
	} else {
		ko.Spec.DNSNameServers = nil
	}
	if resp.ReplicationInstance.EngineVersion != nil {
		ko.Spec.EngineVersion = resp.ReplicationInstance.EngineVersion
	} else {
		ko.Spec.EngineVersion = nil
	}
	if resp.ReplicationInstance.FreeUntil != nil {
		ko.Status.FreeUntil = &metav1.Time{*resp.ReplicationInstance.FreeUntil}
	} else {
		ko.Status.FreeUntil = nil
	}
	if resp.ReplicationInstance.InstanceCreateTime != nil {
		ko.Status.InstanceCreateTime = &metav1.Time{*resp.ReplicationInstance.InstanceCreateTime}
	} else {
		ko.Status.InstanceCreateTime = nil
	}
	if resp.ReplicationInstance.KerberosAuthenticationSettings != nil {
		f7 := &svcapitypes.KerberosAuthenticationSettings{}
		if resp.ReplicationInstance.KerberosAuthenticationSettings.KeyCacheSecretIamArn != nil {
			f7.KeyCacheSecretIAMARN = resp.ReplicationInstance.KerberosAuthenticationSettings.KeyCacheSecretIamArn
		}
		if resp.ReplicationInstance.KerberosAuthenticationSettings.KeyCacheSecretId != nil {
			f7.KeyCacheSecretID = resp.ReplicationInstance.KerberosAuthenticationSettings.KeyCacheSecretId
		}
		if resp.ReplicationInstance.KerberosAuthenticationSettings.Krb5FileContents != nil {
			f7.Krb5FileContents = resp.ReplicationInstance.KerberosAuthenticationSettings.Krb5FileContents
		}
		ko.Spec.KerberosAuthenticationSettings = f7
	} else {
		ko.Spec.KerberosAuthenticationSettings = nil
	}
	if resp.ReplicationInstance.KmsKeyId != nil {
		ko.Spec.KMSKeyID = resp.ReplicationInstance.KmsKeyId
	} else {
		ko.Spec.KMSKeyID = nil
	}
	ko.Spec.MultiAZ = &resp.ReplicationInstance.MultiAZ
	if resp.ReplicationInstance.NetworkType != nil {
		ko.Spec.NetworkType = resp.ReplicationInstance.NetworkType
	} else {
		ko.Spec.NetworkType = nil
	}
	if resp.ReplicationInstance.PendingModifiedValues != nil {
		f11 := &svcapitypes.ReplicationPendingModifiedValues{}
		if resp.ReplicationInstance.PendingModifiedValues.AllocatedStorage != nil {
			allocatedStorageCopy := int64(*resp.ReplicationInstance.PendingModifiedValues.AllocatedStorage)
			f11.AllocatedStorage = &allocatedStorageCopy
		}
		if resp.ReplicationInstance.PendingModifiedValues.EngineVersion != nil {
			f11.EngineVersion = resp.ReplicationInstance.PendingModifiedValues.EngineVersion
		}
		if resp.ReplicationInstance.PendingModifiedValues.MultiAZ != nil {
			f11.MultiAZ = resp.ReplicationInstance.PendingModifiedValues.MultiAZ
		}
		if resp.ReplicationInstance.PendingModifiedValues.NetworkType != nil {
			f11.NetworkType = resp.ReplicationInstance.PendingModifiedValues.NetworkType
		}
		if resp.ReplicationInstance.PendingModifiedValues.ReplicationInstanceClass != nil {
			f11.ReplicationInstanceClass = resp.ReplicationInstance.PendingModifiedValues.ReplicationInstanceClass
		}
		ko.Status.PendingModifiedValues = f11
	} else {
		ko.Status.PendingModifiedValues = nil
	}
	if resp.ReplicationInstance.PreferredMaintenanceWindow != nil {
		ko.Spec.PreferredMaintenanceWindow = resp.ReplicationInstance.PreferredMaintenanceWindow
	} else {
		ko.Spec.PreferredMaintenanceWindow = nil
	}
	ko.Spec.PubliclyAccessible = &resp.ReplicationInstance.PubliclyAccessible
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.ReplicationInstance.ReplicationInstanceArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.ReplicationInstance.ReplicationInstanceArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.ReplicationInstance.ReplicationInstanceClass != nil {
		ko.Spec.InstanceClass = resp.ReplicationInstance.ReplicationInstanceClass
	} else {
		ko.Spec.InstanceClass = nil
	}
	if resp.ReplicationInstance.ReplicationInstanceIdentifier != nil {
		ko.Spec.Name = resp.ReplicationInstance.ReplicationInstanceIdentifier
	} else {
		ko.Spec.Name = nil
	}
	if resp.ReplicationInstance.ReplicationInstanceIpv6Addresses != nil {
		ko.Status.ReplicationInstanceIPv6Addresses = aws.StringSlice(resp.ReplicationInstance.ReplicationInstanceIpv6Addresses)
	} else {
		ko.Status.ReplicationInstanceIPv6Addresses = nil
	}
	if resp.ReplicationInstance.ReplicationInstancePrivateIpAddress != nil {
		ko.Status.ReplicationInstancePrivateIPAddress = resp.ReplicationInstance.ReplicationInstancePrivateIpAddress
	} else {
		ko.Status.ReplicationInstancePrivateIPAddress = nil
	}
	if resp.ReplicationInstance.ReplicationInstancePrivateIpAddresses != nil {
		ko.Status.ReplicationInstancePrivateIPAddresses = aws.StringSlice(resp.ReplicationInstance.ReplicationInstancePrivateIpAddresses)
	} else {
		ko.Status.ReplicationInstancePrivateIPAddresses = nil
	}
	if resp.ReplicationInstance.ReplicationInstancePublicIpAddress != nil {
		ko.Status.ReplicationInstancePublicIPAddress = resp.ReplicationInstance.ReplicationInstancePublicIpAddress
	} else {
		ko.Status.ReplicationInstancePublicIPAddress = nil
	}
	if resp.ReplicationInstance.ReplicationInstancePublicIpAddresses != nil {
		ko.Status.ReplicationInstancePublicIPAddresses = aws.StringSlice(resp.ReplicationInstance.ReplicationInstancePublicIpAddresses)
	} else {
		ko.Status.ReplicationInstancePublicIPAddresses = nil
	}
	if resp.ReplicationInstance.ReplicationInstanceStatus != nil {
		ko.Status.ReplicationInstanceStatus = resp.ReplicationInstance.ReplicationInstanceStatus
	} else {
		ko.Status.ReplicationInstanceStatus = nil
	}
	if resp.ReplicationInstance.ReplicationSubnetGroup != nil {
		f23 := &svcapitypes.ReplicationSubnetGroup_SDK{}
		if resp.ReplicationInstance.ReplicationSubnetGroup.IsReadOnly != nil {
			f23.IsReadOnly = resp.ReplicationInstance.ReplicationSubnetGroup.IsReadOnly
		}
		if resp.ReplicationInstance.ReplicationSubnetGroup.ReplicationSubnetGroupDescription != nil {
			f23.ReplicationSubnetGroupDescription = resp.ReplicationInstance.ReplicationSubnetGroup.ReplicationSubnetGroupDescription
		}
		if resp.ReplicationInstance.ReplicationSubnetGroup.ReplicationSubnetGroupIdentifier != nil {
			f23.ReplicationSubnetGroupIdentifier = resp.ReplicationInstance.ReplicationSubnetGroup.ReplicationSubnetGroupIdentifier
		}
		if resp.ReplicationInstance.ReplicationSubnetGroup.SubnetGroupStatus != nil {
			f23.SubnetGroupStatus = resp.ReplicationInstance.ReplicationSubnetGroup.SubnetGroupStatus
		}
		if resp.ReplicationInstance.ReplicationSubnetGroup.Subnets != nil {
			f23f4 := []*svcapitypes.Subnet{}
			for _, f23f4iter := range resp.ReplicationInstance.ReplicationSubnetGroup.Subnets {
				f23f4elem := &svcapitypes.Subnet{}
				if f23f4iter.SubnetAvailabilityZone != nil {
					f23f4elemf0 := &svcapitypes.AvailabilityZone{}
					if f23f4iter.SubnetAvailabilityZone.Name != nil {
						f23f4elemf0.Name = f23f4iter.SubnetAvailabilityZone.Name
					}
					f23f4elem.SubnetAvailabilityZone = f23f4elemf0
				}
				if f23f4iter.SubnetIdentifier != nil {
					f23f4elem.SubnetIdentifier = f23f4iter.SubnetIdentifier
				}
				if f23f4iter.SubnetStatus != nil {
					f23f4elem.SubnetStatus = f23f4iter.SubnetStatus
				}
				f23f4 = append(f23f4, f23f4elem)
			}
			f23.Subnets = f23f4
		}
		if resp.ReplicationInstance.ReplicationSubnetGroup.SupportedNetworkTypes != nil {
			f23.SupportedNetworkTypes = aws.StringSlice(resp.ReplicationInstance.ReplicationSubnetGroup.SupportedNetworkTypes)
		}
		if resp.ReplicationInstance.ReplicationSubnetGroup.VpcId != nil {
			f23.VPCID = resp.ReplicationInstance.ReplicationSubnetGroup.VpcId
		}
		ko.Status.ReplicationSubnetGroup = f23
	} else {
		ko.Status.ReplicationSubnetGroup = nil
	}
	if resp.ReplicationInstance.SecondaryAvailabilityZone != nil {
		ko.Status.SecondaryAvailabilityZone = resp.ReplicationInstance.SecondaryAvailabilityZone
	} else {
		ko.Status.SecondaryAvailabilityZone = nil
	}
	if resp.ReplicationInstance.VpcSecurityGroups != nil {
		f25 := []*svcapitypes.VPCSecurityGroupMembership{}
		for _, f25iter := range resp.ReplicationInstance.VpcSecurityGroups {
			f25elem := &svcapitypes.VPCSecurityGroupMembership{}
			if f25iter.Status != nil {
				f25elem.Status = f25iter.Status
			}
			if f25iter.VpcSecurityGroupId != nil {
				f25elem.VPCSecurityGroupID = f25iter.VpcSecurityGroupId
			}
			f25 = append(f25, f25elem)
		}
		ko.Status.VPCSecurityGroups = f25
	} else {
		ko.Status.VPCSecurityGroups = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateReplicationInstanceInput, error) {
	res := &svcsdk.CreateReplicationInstanceInput{}

	if r.ko.Spec.AllocatedStorage != nil {
		allocatedStorageCopy0 := *r.ko.Spec.AllocatedStorage
		if allocatedStorageCopy0 > math.MaxInt32 || allocatedStorageCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field AllocatedStorage is of type int32")
		}
		allocatedStorageCopy := int32(allocatedStorageCopy0)
		res.AllocatedStorage = &allocatedStorageCopy
	}
	if r.ko.Spec.AutoMinorVersionUpgrade != nil {
		res.AutoMinorVersionUpgrade = r.ko.Spec.AutoMinorVersionUpgrade
	}
	if r.ko.Spec.AvailabilityZone != nil {
		res.AvailabilityZone = r.ko.Spec.AvailabilityZone
	}
	if r.ko.Spec.DNSNameServers != nil {
		res.DnsNameServers = r.ko.Spec.DNSNameServers
	}
	if r.ko.Spec.EngineVersion != nil {
		res.EngineVersion = r.ko.Spec.EngineVersion
	}
	if r.ko.Spec.KerberosAuthenticationSettings != nil {
		f5 := &svcsdktypes.KerberosAuthenticationSettings{}
		if r.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretIAMARN != nil {
			f5.KeyCacheSecretIamArn = r.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretIAMARN
		}
		if r.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretID != nil {
			f5.KeyCacheSecretId = r.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretID
		}
		if r.ko.Spec.KerberosAuthenticationSettings.Krb5FileContents != nil {
			f5.Krb5FileContents = r.ko.Spec.KerberosAuthenticationSettings.Krb5FileContents
		}
		res.KerberosAuthenticationSettings = f5
	}
	if r.ko.Spec.KMSKeyID != nil {
		res.KmsKeyId = r.ko.Spec.KMSKeyID
	}
	if r.ko.Spec.MultiAZ != nil {
		res.MultiAZ = r.ko.Spec.MultiAZ
	}
	if r.ko.Spec.NetworkType != nil {
		res.NetworkType = r.ko.Spec.NetworkType
	}
	if r.ko.Spec.PreferredMaintenanceWindow != nil {
		res.PreferredMaintenanceWindow = r.ko.Spec.PreferredMaintenanceWindow
	}
	if r.ko.Spec.PubliclyAccessible != nil {
		res.PubliclyAccessible = r.ko.Spec.PubliclyAccessible
	}
	if r.ko.Spec.InstanceClass != nil {
		res.ReplicationInstanceClass = r.ko.Spec.InstanceClass
	}
	if r.ko.Spec.Name != nil {
		res.ReplicationInstanceIdentifier = r.ko.Spec.Name
	}
	if r.ko.Spec.SubnetGroupID != nil {
		res.ReplicationSubnetGroupIdentifier = r.ko.Spec.SubnetGroupID
	}
	if r.ko.Spec.ResourceIdentifier != nil {
		res.ResourceIdentifier = r.ko.Spec.ResourceIdentifier
	}
	if r.ko.Spec.Tags != nil {
		f15 := []svcsdktypes.Tag{}
		for _, f15iter := range r.ko.Spec.Tags {
			f15elem := &svcsdktypes.Tag{}
			if f15iter.Key != nil {
				f15elem.Key = f15iter.Key
			}
			if f15iter.ResourceARN != nil {
				f15elem.ResourceArn = f15iter.ResourceARN
			}
			if f15iter.Value != nil {
				f15elem.Value = f15iter.Value
			}
			f15 = append(f15, *f15elem)
		}
		res.Tags = f15
	}
	if r.ko.Spec.SecurityGroupIDs != nil {
		res.VpcSecurityGroupIds = aws.ToStringSlice(r.ko.Spec.SecurityGroupIDs)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.ModifyReplicationInstanceOutput
	_ = resp
	resp, err = rm.sdkapi.ModifyReplicationInstance(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "ModifyReplicationInstance", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	// sdk_update_pre_set_output hook
	if latest.ko.ObjectMeta.GetDeletionTimestamp() == nil {
		if delta.DifferentAt("Spec.Tags") {
			if err = rm.syncTags(ctx, desired, latest); err != nil {
				return nil, err
			}
		}
	}

	allocatedStorageCopy := int64(resp.ReplicationInstance.AllocatedStorage)
	ko.Spec.AllocatedStorage = &allocatedStorageCopy
	ko.Spec.AutoMinorVersionUpgrade = &resp.ReplicationInstance.AutoMinorVersionUpgrade
	if resp.ReplicationInstance.AvailabilityZone != nil {
		ko.Spec.AvailabilityZone = resp.ReplicationInstance.AvailabilityZone
	} else {
		ko.Spec.AvailabilityZone = nil
	}
	if resp.ReplicationInstance.DnsNameServers != nil {
		ko.Spec.DNSNameServers = resp.ReplicationInstance.DnsNameServers
	} else {
		ko.Spec.DNSNameServers = nil
	}
	if resp.ReplicationInstance.EngineVersion != nil {
		ko.Spec.EngineVersion = resp.ReplicationInstance.EngineVersion
	} else {
		ko.Spec.EngineVersion = nil
	}
	if resp.ReplicationInstance.FreeUntil != nil {
		ko.Status.FreeUntil = &metav1.Time{*resp.ReplicationInstance.FreeUntil}
	} else {
		ko.Status.FreeUntil = nil
	}
	if resp.ReplicationInstance.InstanceCreateTime != nil {
		ko.Status.InstanceCreateTime = &metav1.Time{*resp.ReplicationInstance.InstanceCreateTime}
	} else {
		ko.Status.InstanceCreateTime = nil
	}
	if resp.ReplicationInstance.KerberosAuthenticationSettings != nil {
		f7 := &svcapitypes.KerberosAuthenticationSettings{}
		if resp.ReplicationInstance.KerberosAuthenticationSettings.KeyCacheSecretIamArn != nil {
			f7.KeyCacheSecretIAMARN = resp.ReplicationInstance.KerberosAuthenticationSettings.KeyCacheSecretIamArn
		}
		if resp.ReplicationInstance.KerberosAuthenticationSettings.KeyCacheSecretId != nil {
			f7.KeyCacheSecretID = resp.ReplicationInstance.KerberosAuthenticationSettings.KeyCacheSecretId
		}
		if resp.ReplicationInstance.KerberosAuthenticationSettings.Krb5FileContents != nil {
			f7.Krb5FileContents = resp.ReplicationInstance.KerberosAuthenticationSettings.Krb5FileContents
		}
		ko.Spec.KerberosAuthenticationSettings = f7
	} else {
		ko.Spec.KerberosAuthenticationSettings = nil
	}
	if resp.ReplicationInstance.KmsKeyId != nil {
		ko.Spec.KMSKeyID = resp.ReplicationInstance.KmsKeyId
	} else {
		ko.Spec.KMSKeyID = nil
	}
	ko.Spec.MultiAZ = &resp.ReplicationInstance.MultiAZ
	if resp.ReplicationInstance.NetworkType != nil {
		ko.Spec.NetworkType = resp.ReplicationInstance.NetworkType
	} else {
		ko.Spec.NetworkType = nil
	}
	if resp.ReplicationInstance.PendingModifiedValues != nil {
		f11 := &svcapitypes.ReplicationPendingModifiedValues{}
		if resp.ReplicationInstance.PendingModifiedValues.AllocatedStorage != nil {
			allocatedStorageCopy := int64(*resp.ReplicationInstance.PendingModifiedValues.AllocatedStorage)
			f11.AllocatedStorage = &allocatedStorageCopy
		}
		if resp.ReplicationInstance.PendingModifiedValues.EngineVersion != nil {
			f11.EngineVersion = resp.ReplicationInstance.PendingModifiedValues.EngineVersion
		}
		if resp.ReplicationInstance.PendingModifiedValues.MultiAZ != nil {
			f11.MultiAZ = resp.ReplicationInstance.PendingModifiedValues.MultiAZ
		}
		if resp.ReplicationInstance.PendingModifiedValues.NetworkType != nil {
			f11.NetworkType = resp.ReplicationInstance.PendingModifiedValues.NetworkType
		}
		if resp.ReplicationInstance.PendingModifiedValues.ReplicationInstanceClass != nil {
			f11.ReplicationInstanceClass = resp.ReplicationInstance.PendingModifiedValues.ReplicationInstanceClass
		}
		ko.Status.PendingModifiedValues = f11
	} else {
		ko.Status.PendingModifiedValues = nil
	}
	if resp.ReplicationInstance.PreferredMaintenanceWindow != nil {
		ko.Spec.PreferredMaintenanceWindow = resp.ReplicationInstance.PreferredMaintenanceWindow
	} else {
		ko.Spec.PreferredMaintenanceWindow = nil
	}
	ko.Spec.PubliclyAccessible = &resp.ReplicationInstance.PubliclyAccessible
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.ReplicationInstance.ReplicationInstanceArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.ReplicationInstance.ReplicationInstanceArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.ReplicationInstance.ReplicationInstanceClass != nil {
		ko.Spec.InstanceClass = resp.ReplicationInstance.ReplicationInstanceClass
	} else {
		ko.Spec.InstanceClass = nil
	}
	if resp.ReplicationInstance.ReplicationInstanceIdentifier != nil {
		ko.Spec.Name = resp.ReplicationInstance.ReplicationInstanceIdentifier
	} else {
		ko.Spec.Name = nil
	}
	if resp.ReplicationInstance.ReplicationInstanceIpv6Addresses != nil {
		ko.Status.ReplicationInstanceIPv6Addresses = aws.StringSlice(resp.ReplicationInstance.ReplicationInstanceIpv6Addresses)
	} else {
		ko.Status.ReplicationInstanceIPv6Addresses = nil
	}
	if resp.ReplicationInstance.ReplicationInstancePrivateIpAddress != nil {
		ko.Status.ReplicationInstancePrivateIPAddress = resp.ReplicationInstance.ReplicationInstancePrivateIpAddress
	} else {
		ko.Status.ReplicationInstancePrivateIPAddress = nil
	}
	if resp.ReplicationInstance.ReplicationInstancePrivateIpAddresses != nil {
		ko.Status.ReplicationInstancePrivateIPAddresses = aws.StringSlice(resp.ReplicationInstance.ReplicationInstancePrivateIpAddresses)
	} else {
		ko.Status.ReplicationInstancePrivateIPAddresses = nil
	}
	if resp.ReplicationInstance.ReplicationInstancePublicIpAddress != nil {
		ko.Status.ReplicationInstancePublicIPAddress = resp.ReplicationInstance.ReplicationInstancePublicIpAddress
	} else {
		ko.Status.ReplicationInstancePublicIPAddress = nil
	}
	if resp.ReplicationInstance.ReplicationInstancePublicIpAddresses != nil {
		ko.Status.ReplicationInstancePublicIPAddresses = aws.StringSlice(resp.ReplicationInstance.ReplicationInstancePublicIpAddresses)
	} else {
		ko.Status.ReplicationInstancePublicIPAddresses = nil
	}
	if resp.ReplicationInstance.ReplicationInstanceStatus != nil {
		ko.Status.ReplicationInstanceStatus = resp.ReplicationInstance.ReplicationInstanceStatus
	} else {
		ko.Status.ReplicationInstanceStatus = nil
	}
	if resp.ReplicationInstance.ReplicationSubnetGroup != nil {
		f23 := &svcapitypes.ReplicationSubnetGroup_SDK{}
		if resp.ReplicationInstance.ReplicationSubnetGroup.IsReadOnly != nil {
			f23.IsReadOnly = resp.ReplicationInstance.ReplicationSubnetGroup.IsReadOnly
		}
		if resp.ReplicationInstance.ReplicationSubnetGroup.ReplicationSubnetGroupDescription != nil {
			f23.ReplicationSubnetGroupDescription = resp.ReplicationInstance.ReplicationSubnetGroup.ReplicationSubnetGroupDescription
		}
		if resp.ReplicationInstance.ReplicationSubnetGroup.ReplicationSubnetGroupIdentifier != nil {
			f23.ReplicationSubnetGroupIdentifier = resp.ReplicationInstance.ReplicationSubnetGroup.ReplicationSubnetGroupIdentifier
		}
		if resp.ReplicationInstance.ReplicationSubnetGroup.SubnetGroupStatus != nil {
			f23.SubnetGroupStatus = resp.ReplicationInstance.ReplicationSubnetGroup.SubnetGroupStatus
		}
		if resp.ReplicationInstance.ReplicationSubnetGroup.Subnets != nil {
			f23f4 := []*svcapitypes.Subnet{}
			for _, f23f4iter := range resp.ReplicationInstance.ReplicationSubnetGroup.Subnets {
				f23f4elem := &svcapitypes.Subnet{}
				if f23f4iter.SubnetAvailabilityZone != nil {
					f23f4elemf0 := &svcapitypes.AvailabilityZone{}
					if f23f4iter.SubnetAvailabilityZone.Name != nil {
						f23f4elemf0.Name = f23f4iter.SubnetAvailabilityZone.Name
					}
					f23f4elem.SubnetAvailabilityZone = f23f4elemf0
				}
				if f23f4iter.SubnetIdentifier != nil {
					f23f4elem.SubnetIdentifier = f23f4iter.SubnetIdentifier
				}
				if f23f4iter.SubnetStatus != nil {
					f23f4elem.SubnetStatus = f23f4iter.SubnetStatus
				}
				f23f4 = append(f23f4, f23f4elem)
			}
			f23.Subnets = f23f4
		}
		if resp.ReplicationInstance.ReplicationSubnetGroup.SupportedNetworkTypes != nil {
			f23.SupportedNetworkTypes = aws.StringSlice(resp.ReplicationInstance.ReplicationSubnetGroup.SupportedNetworkTypes)
		}
		if resp.ReplicationInstance.ReplicationSubnetGroup.VpcId != nil {
			f23.VPCID = resp.ReplicationInstance.ReplicationSubnetGroup.VpcId
		}
		ko.Status.ReplicationSubnetGroup = f23
	} else {
		ko.Status.ReplicationSubnetGroup = nil
	}
	if resp.ReplicationInstance.SecondaryAvailabilityZone != nil {
		ko.Status.SecondaryAvailabilityZone = resp.ReplicationInstance.SecondaryAvailabilityZone
	} else {
		ko.Status.SecondaryAvailabilityZone = nil
	}
	if resp.ReplicationInstance.VpcSecurityGroups != nil {
		f25 := []*svcapitypes.VPCSecurityGroupMembership{}
		for _, f25iter := range resp.ReplicationInstance.VpcSecurityGroups {
			f25elem := &svcapitypes.VPCSecurityGroupMembership{}
			if f25iter.Status != nil {
				f25elem.Status = f25iter.Status
			}
			if f25iter.VpcSecurityGroupId != nil {
				f25elem.VPCSecurityGroupID = f25iter.VpcSecurityGroupId
			}
			f25 = append(f25, f25elem)
		}
		ko.Status.VPCSecurityGroups = f25
	} else {
		ko.Status.VPCSecurityGroups = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.ModifyReplicationInstanceInput, error) {
	res := &svcsdk.ModifyReplicationInstanceInput{}

	if r.ko.Spec.AllocatedStorage != nil {
		allocatedStorageCopy0 := *r.ko.Spec.AllocatedStorage
		if allocatedStorageCopy0 > math.MaxInt32 || allocatedStorageCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field AllocatedStorage is of type int32")
		}
		allocatedStorageCopy := int32(allocatedStorageCopy0)
		res.AllocatedStorage = &allocatedStorageCopy
	}
	res.AllowMajorVersionUpgrade = true
	res.ApplyImmediately = true
	if r.ko.Spec.AutoMinorVersionUpgrade != nil {
		res.AutoMinorVersionUpgrade = r.ko.Spec.AutoMinorVersionUpgrade
	}
	if r.ko.Spec.EngineVersion != nil {
		res.EngineVersion = r.ko.Spec.EngineVersion
	}
	if r.ko.Spec.KerberosAuthenticationSettings != nil {
		f5 := &svcsdktypes.KerberosAuthenticationSettings{}
		if r.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretIAMARN != nil {
			f5.KeyCacheSecretIamArn = r.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretIAMARN
		}
		if r.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretID != nil {
			f5.KeyCacheSecretId = r.ko.Spec.KerberosAuthenticationSettings.KeyCacheSecretID
		}
		if r.ko.Spec.KerberosAuthenticationSettings.Krb5FileContents != nil {
			f5.Krb5FileContents = r.ko.Spec.KerberosAuthenticationSettings.Krb5FileContents
		}
		res.KerberosAuthenticationSettings = f5
	}
	if r.ko.Spec.MultiAZ != nil {
		res.MultiAZ = r.ko.Spec.MultiAZ
	}
	if r.ko.Spec.NetworkType != nil {
		res.NetworkType = r.ko.Spec.NetworkType
	}
	if r.ko.Spec.PreferredMaintenanceWindow != nil {
		res.PreferredMaintenanceWindow = r.ko.Spec.PreferredMaintenanceWindow
	}
	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.ReplicationInstanceArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}
	if r.ko.Spec.InstanceClass != nil {
		res.ReplicationInstanceClass = r.ko.Spec.InstanceClass
	}
	if r.ko.Spec.Name != nil {
		res.ReplicationInstanceIdentifier = r.ko.Spec.Name
	}
	if r.ko.Spec.SecurityGroupIDs != nil {
		res.VpcSecurityGroupIds = aws.ToStringSlice(r.ko.Spec.SecurityGroupIDs)
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteReplicationInstanceOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteReplicationInstance(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteReplicationInstance", err)

	// sdk_delete_post_request hook
	//
	// Wait for the replication instance to be deleted before setResourceUnmanaged.
	if err != nil {
		return nil, err
	}
	r.ko.Status.ReplicationInstanceStatus = aws.String(replicationInstanceStatusDeleting)
	return r, ackrequeue.NeededAfter(errors.New("Waiting for ReplicationInstance deletion to complete"), 10*time.Second)

	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteReplicationInstanceInput, error) {
	res := &svcsdk.DeleteReplicationInstanceInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.ReplicationInstanceArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.ReplicationInstance,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	if syncCondition == nil && onSuccess {
		syncCondition = &ackv1alpha1.Condition{
			Type:   ackv1alpha1.ConditionTypeResourceSynced,
			Status: corev1.ConditionTrue,
		}
		ko.Status.Conditions = append(ko.Status.Conditions, syncCondition)
	}
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
