---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ack-dms-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dms.services.k8s.aws
  resources:
  - certificates
  - endpoints
  - eventsubscriptions
  - replicationinstances
  - replicationsubnetgroups
  - replicationtasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dms.services.k8s.aws
  resources:
  - certificates/status
  - endpoints/status
  - eventsubscriptions/status
  - replicationinstances/status
  - replicationsubnetgroups/status
  - replicationtasks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ec2.services.k8s.aws
  resources:
  - securitygroups
  - securitygroups/status
  - subnets
  - subnets/status
  verbs:
  - get
  - list
- apiGroups:
  - iam.services.k8s.aws
  resources:
  - roles
  - roles/status
  verbs:
  - get
  - list
- apiGroups:
  - kinesis.services.k8s.aws
  resources:
  - streams
  - streams/status
  verbs:
  - get
  - list
- apiGroups:
  - kms.services.k8s.aws
  resources:
  - keys
  - keys/status
  verbs:
  - get
  - list
- apiGroups:
  - s3.services.k8s.aws
  resources:
  - buckets
  - buckets/status
  verbs:
  - get
  - list
- apiGroups:
  - secretsmanager.services.k8s.aws
  resources:
  - secrets
  - secrets/status
  verbs:
  - get
  - list
- apiGroups:
  - services.k8s.aws
  resources:
  - fieldexports
  - iamroleselectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - services.k8s.aws
  resources:
  - fieldexports/status
  - iamroleselectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sns.services.k8s.aws
  resources:
  - topics
  - topics/status
  verbs:
  - get
  - list
