// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package replication_subnet_group

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"
	"time"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/databasemigrationservice"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/databasemigrationservice/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/dms-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.ReplicationSubnetGroup{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}

	// sdk_read_many_post_build_request hook
	//
	// DescribeReplicationSubnetGroups does not provide any identifier input fields,
	// so we need to build a filter on our own.
	input.Filters = []svcsdktypes.Filter{
		{
			Name:   aws.String("replication-subnet-group-id"),
			Values: []string{aws.ToString(r.ko.Spec.Name)},
		},
	}

	var resp *svcsdk.DescribeReplicationSubnetGroupsOutput
	resp, err = rm.sdkapi.DescribeReplicationSubnetGroups(ctx, input)

	// sdk_read_many_post_request hook
	//
	// Map ResourceNotFoundFault to NotFound error so ACK can trigger createResource
	// correctly.
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundFault" {
			rm.metrics.RecordAPICall("READ_MANY", "DescribeReplicationSubnetGroups", err)
			return nil, ackerr.NotFound
		}
	}

	rm.metrics.RecordAPICall("READ_MANY", "DescribeReplicationSubnetGroups", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.ReplicationSubnetGroups {
		if elem.IsReadOnly != nil {
			ko.Status.IsReadOnly = elem.IsReadOnly
		} else {
			ko.Status.IsReadOnly = nil
		}
		if elem.ReplicationSubnetGroupDescription != nil {
			ko.Spec.Description = elem.ReplicationSubnetGroupDescription
		} else {
			ko.Spec.Description = nil
		}
		if elem.ReplicationSubnetGroupIdentifier != nil {
			ko.Spec.Name = elem.ReplicationSubnetGroupIdentifier
		} else {
			ko.Spec.Name = nil
		}
		if elem.SubnetGroupStatus != nil {
			ko.Status.SubnetGroupStatus = elem.SubnetGroupStatus
		} else {
			ko.Status.SubnetGroupStatus = nil
		}
		if elem.Subnets != nil {
			f4 := []*svcapitypes.Subnet{}
			for _, f4iter := range elem.Subnets {
				f4elem := &svcapitypes.Subnet{}
				if f4iter.SubnetAvailabilityZone != nil {
					f4elemf0 := &svcapitypes.AvailabilityZone{}
					if f4iter.SubnetAvailabilityZone.Name != nil {
						f4elemf0.Name = f4iter.SubnetAvailabilityZone.Name
					}
					f4elem.SubnetAvailabilityZone = f4elemf0
				}
				if f4iter.SubnetIdentifier != nil {
					f4elem.SubnetIdentifier = f4iter.SubnetIdentifier
				}
				if f4iter.SubnetStatus != nil {
					f4elem.SubnetStatus = f4iter.SubnetStatus
				}
				f4 = append(f4, f4elem)
			}
			ko.Status.Subnets = f4
		} else {
			ko.Status.Subnets = nil
		}
		if elem.SupportedNetworkTypes != nil {
			ko.Status.SupportedNetworkTypes = aws.StringSlice(elem.SupportedNetworkTypes)
		} else {
			ko.Status.SupportedNetworkTypes = nil
		}
		if elem.VpcId != nil {
			ko.Status.VPCID = elem.VpcId
		} else {
			ko.Status.VPCID = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)

	// sdk_read_many_post_set_output hook
	//
	// The API does not return the ARN so we build it ourselves.
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.ARN == nil {
		arn := ackv1alpha1.AWSResourceName(fmt.Sprintf(
			"arn:%s:dms:%s:%s:subgrp:%s",
			partitionFromRegion(string(rm.awsRegion)),
			rm.awsRegion,
			rm.awsAccountID,
			*ko.Spec.Name,
		))
		ko.Status.ACKResourceMetadata.ARN = &arn
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return false
}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeReplicationSubnetGroupsInput, error) {
	res := &svcsdk.DescribeReplicationSubnetGroupsInput{}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateReplicationSubnetGroupOutput
	_ = resp
	resp, err = rm.sdkapi.CreateReplicationSubnetGroup(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateReplicationSubnetGroup", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.ReplicationSubnetGroup.IsReadOnly != nil {
		ko.Status.IsReadOnly = resp.ReplicationSubnetGroup.IsReadOnly
	} else {
		ko.Status.IsReadOnly = nil
	}
	if resp.ReplicationSubnetGroup.ReplicationSubnetGroupDescription != nil {
		ko.Spec.Description = resp.ReplicationSubnetGroup.ReplicationSubnetGroupDescription
	} else {
		ko.Spec.Description = nil
	}
	if resp.ReplicationSubnetGroup.ReplicationSubnetGroupIdentifier != nil {
		ko.Spec.Name = resp.ReplicationSubnetGroup.ReplicationSubnetGroupIdentifier
	} else {
		ko.Spec.Name = nil
	}
	if resp.ReplicationSubnetGroup.SubnetGroupStatus != nil {
		ko.Status.SubnetGroupStatus = resp.ReplicationSubnetGroup.SubnetGroupStatus
	} else {
		ko.Status.SubnetGroupStatus = nil
	}
	if resp.ReplicationSubnetGroup.Subnets != nil {
		f4 := []*svcapitypes.Subnet{}
		for _, f4iter := range resp.ReplicationSubnetGroup.Subnets {
			f4elem := &svcapitypes.Subnet{}
			if f4iter.SubnetAvailabilityZone != nil {
				f4elemf0 := &svcapitypes.AvailabilityZone{}
				if f4iter.SubnetAvailabilityZone.Name != nil {
					f4elemf0.Name = f4iter.SubnetAvailabilityZone.Name
				}
				f4elem.SubnetAvailabilityZone = f4elemf0
			}
			if f4iter.SubnetIdentifier != nil {
				f4elem.SubnetIdentifier = f4iter.SubnetIdentifier
			}
			if f4iter.SubnetStatus != nil {
				f4elem.SubnetStatus = f4iter.SubnetStatus
			}
			f4 = append(f4, f4elem)
		}
		ko.Status.Subnets = f4
	} else {
		ko.Status.Subnets = nil
	}
	if resp.ReplicationSubnetGroup.SupportedNetworkTypes != nil {
		ko.Status.SupportedNetworkTypes = aws.StringSlice(resp.ReplicationSubnetGroup.SupportedNetworkTypes)
	} else {
		ko.Status.SupportedNetworkTypes = nil
	}
	if resp.ReplicationSubnetGroup.VpcId != nil {
		ko.Status.VPCID = resp.ReplicationSubnetGroup.VpcId
	} else {
		ko.Status.VPCID = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateReplicationSubnetGroupInput, error) {
	res := &svcsdk.CreateReplicationSubnetGroupInput{}

	if r.ko.Spec.Description != nil {
		res.ReplicationSubnetGroupDescription = r.ko.Spec.Description
	}
	if r.ko.Spec.Name != nil {
		res.ReplicationSubnetGroupIdentifier = r.ko.Spec.Name
	}
	if r.ko.Spec.SubnetIDs != nil {
		res.SubnetIds = aws.ToStringSlice(r.ko.Spec.SubnetIDs)
	}
	if r.ko.Spec.Tags != nil {
		f3 := []svcsdktypes.Tag{}
		for _, f3iter := range r.ko.Spec.Tags {
			f3elem := &svcsdktypes.Tag{}
			if f3iter.Key != nil {
				f3elem.Key = f3iter.Key
			}
			if f3iter.ResourceARN != nil {
				f3elem.ResourceArn = f3iter.ResourceARN
			}
			if f3iter.Value != nil {
				f3elem.Value = f3iter.Value
			}
			f3 = append(f3, *f3elem)
		}
		res.Tags = f3
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.ModifyReplicationSubnetGroupOutput
	_ = resp
	resp, err = rm.sdkapi.ModifyReplicationSubnetGroup(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "ModifyReplicationSubnetGroup", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.ReplicationSubnetGroup.IsReadOnly != nil {
		ko.Status.IsReadOnly = resp.ReplicationSubnetGroup.IsReadOnly
	} else {
		ko.Status.IsReadOnly = nil
	}
	if resp.ReplicationSubnetGroup.ReplicationSubnetGroupDescription != nil {
		ko.Spec.Description = resp.ReplicationSubnetGroup.ReplicationSubnetGroupDescription
	} else {
		ko.Spec.Description = nil
	}
	if resp.ReplicationSubnetGroup.ReplicationSubnetGroupIdentifier != nil {
		ko.Spec.Name = resp.ReplicationSubnetGroup.ReplicationSubnetGroupIdentifier
	} else {
		ko.Spec.Name = nil
	}
	if resp.ReplicationSubnetGroup.SubnetGroupStatus != nil {
		ko.Status.SubnetGroupStatus = resp.ReplicationSubnetGroup.SubnetGroupStatus
	} else {
		ko.Status.SubnetGroupStatus = nil
	}
	if resp.ReplicationSubnetGroup.Subnets != nil {
		f4 := []*svcapitypes.Subnet{}
		for _, f4iter := range resp.ReplicationSubnetGroup.Subnets {
			f4elem := &svcapitypes.Subnet{}
			if f4iter.SubnetAvailabilityZone != nil {
				f4elemf0 := &svcapitypes.AvailabilityZone{}
				if f4iter.SubnetAvailabilityZone.Name != nil {
					f4elemf0.Name = f4iter.SubnetAvailabilityZone.Name
				}
				f4elem.SubnetAvailabilityZone = f4elemf0
			}
			if f4iter.SubnetIdentifier != nil {
				f4elem.SubnetIdentifier = f4iter.SubnetIdentifier
			}
			if f4iter.SubnetStatus != nil {
				f4elem.SubnetStatus = f4iter.SubnetStatus
			}
			f4 = append(f4, f4elem)
		}
		ko.Status.Subnets = f4
	} else {
		ko.Status.Subnets = nil
	}
	if resp.ReplicationSubnetGroup.SupportedNetworkTypes != nil {
		ko.Status.SupportedNetworkTypes = aws.StringSlice(resp.ReplicationSubnetGroup.SupportedNetworkTypes)
	} else {
		ko.Status.SupportedNetworkTypes = nil
	}
	if resp.ReplicationSubnetGroup.VpcId != nil {
		ko.Status.VPCID = resp.ReplicationSubnetGroup.VpcId
	} else {
		ko.Status.VPCID = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.ModifyReplicationSubnetGroupInput, error) {
	res := &svcsdk.ModifyReplicationSubnetGroupInput{}

	if r.ko.Spec.Description != nil {
		res.ReplicationSubnetGroupDescription = r.ko.Spec.Description
	}
	if r.ko.Spec.Name != nil {
		res.ReplicationSubnetGroupIdentifier = r.ko.Spec.Name
	}
	if r.ko.Spec.SubnetIDs != nil {
		res.SubnetIds = aws.ToStringSlice(r.ko.Spec.SubnetIDs)
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteReplicationSubnetGroupOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteReplicationSubnetGroup(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteReplicationSubnetGroup", err)

	// sdk_delete_post_request hook
	//
	// Wait for the replication subnet group to be deleted before setResourceUnmanaged.
	if err != nil {
		return nil, err
	}
	r.ko.Status.SubnetGroupStatus = aws.String(replicationSubnetGroupStatusDeleting)
	return r, ackrequeue.NeededAfter(errors.New("Waiting for ReplicationSubnetGroup deletion to complete"), 10*time.Second)

	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteReplicationSubnetGroupInput, error) {
	res := &svcsdk.DeleteReplicationSubnetGroupInput{}

	if r.ko.Spec.Name != nil {
		res.ReplicationSubnetGroupIdentifier = r.ko.Spec.Name
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.ReplicationSubnetGroup,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}
