// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package replication_task

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}
	compareTags(delta, a, b)

	if ackcompare.HasNilDifference(a.ko.Spec.CdcStartPosition, b.ko.Spec.CdcStartPosition) {
		delta.Add("Spec.CdcStartPosition", a.ko.Spec.CdcStartPosition, b.ko.Spec.CdcStartPosition)
	} else if a.ko.Spec.CdcStartPosition != nil && b.ko.Spec.CdcStartPosition != nil {
		if *a.ko.Spec.CdcStartPosition != *b.ko.Spec.CdcStartPosition {
			delta.Add("Spec.CdcStartPosition", a.ko.Spec.CdcStartPosition, b.ko.Spec.CdcStartPosition)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.CdcStartTime, b.ko.Spec.CdcStartTime) {
		delta.Add("Spec.CdcStartTime", a.ko.Spec.CdcStartTime, b.ko.Spec.CdcStartTime)
	} else if a.ko.Spec.CdcStartTime != nil && b.ko.Spec.CdcStartTime != nil {
		if !a.ko.Spec.CdcStartTime.Equal(b.ko.Spec.CdcStartTime) {
			delta.Add("Spec.CdcStartTime", a.ko.Spec.CdcStartTime, b.ko.Spec.CdcStartTime)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.CdcStopPosition, b.ko.Spec.CdcStopPosition) {
		delta.Add("Spec.CdcStopPosition", a.ko.Spec.CdcStopPosition, b.ko.Spec.CdcStopPosition)
	} else if a.ko.Spec.CdcStopPosition != nil && b.ko.Spec.CdcStopPosition != nil {
		if *a.ko.Spec.CdcStopPosition != *b.ko.Spec.CdcStopPosition {
			delta.Add("Spec.CdcStopPosition", a.ko.Spec.CdcStopPosition, b.ko.Spec.CdcStopPosition)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MigrationType, b.ko.Spec.MigrationType) {
		delta.Add("Spec.MigrationType", a.ko.Spec.MigrationType, b.ko.Spec.MigrationType)
	} else if a.ko.Spec.MigrationType != nil && b.ko.Spec.MigrationType != nil {
		if *a.ko.Spec.MigrationType != *b.ko.Spec.MigrationType {
			delta.Add("Spec.MigrationType", a.ko.Spec.MigrationType, b.ko.Spec.MigrationType)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ReplicationInstanceARN, b.ko.Spec.ReplicationInstanceARN) {
		delta.Add("Spec.ReplicationInstanceARN", a.ko.Spec.ReplicationInstanceARN, b.ko.Spec.ReplicationInstanceARN)
	} else if a.ko.Spec.ReplicationInstanceARN != nil && b.ko.Spec.ReplicationInstanceARN != nil {
		if *a.ko.Spec.ReplicationInstanceARN != *b.ko.Spec.ReplicationInstanceARN {
			delta.Add("Spec.ReplicationInstanceARN", a.ko.Spec.ReplicationInstanceARN, b.ko.Spec.ReplicationInstanceARN)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ReplicationTaskSettings, b.ko.Spec.ReplicationTaskSettings) {
		delta.Add("Spec.ReplicationTaskSettings", a.ko.Spec.ReplicationTaskSettings, b.ko.Spec.ReplicationTaskSettings)
	} else if a.ko.Spec.ReplicationTaskSettings != nil && b.ko.Spec.ReplicationTaskSettings != nil {
		if *a.ko.Spec.ReplicationTaskSettings != *b.ko.Spec.ReplicationTaskSettings {
			delta.Add("Spec.ReplicationTaskSettings", a.ko.Spec.ReplicationTaskSettings, b.ko.Spec.ReplicationTaskSettings)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ResourceIdentifier, b.ko.Spec.ResourceIdentifier) {
		delta.Add("Spec.ResourceIdentifier", a.ko.Spec.ResourceIdentifier, b.ko.Spec.ResourceIdentifier)
	} else if a.ko.Spec.ResourceIdentifier != nil && b.ko.Spec.ResourceIdentifier != nil {
		if *a.ko.Spec.ResourceIdentifier != *b.ko.Spec.ResourceIdentifier {
			delta.Add("Spec.ResourceIdentifier", a.ko.Spec.ResourceIdentifier, b.ko.Spec.ResourceIdentifier)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SourceEndpointARN, b.ko.Spec.SourceEndpointARN) {
		delta.Add("Spec.SourceEndpointARN", a.ko.Spec.SourceEndpointARN, b.ko.Spec.SourceEndpointARN)
	} else if a.ko.Spec.SourceEndpointARN != nil && b.ko.Spec.SourceEndpointARN != nil {
		if *a.ko.Spec.SourceEndpointARN != *b.ko.Spec.SourceEndpointARN {
			delta.Add("Spec.SourceEndpointARN", a.ko.Spec.SourceEndpointARN, b.ko.Spec.SourceEndpointARN)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.SourceEndpointRef, b.ko.Spec.SourceEndpointRef) {
		delta.Add("Spec.SourceEndpointRef", a.ko.Spec.SourceEndpointRef, b.ko.Spec.SourceEndpointRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.StartReplicationTask, b.ko.Spec.StartReplicationTask) {
		delta.Add("Spec.StartReplicationTask", a.ko.Spec.StartReplicationTask, b.ko.Spec.StartReplicationTask)
	} else if a.ko.Spec.StartReplicationTask != nil && b.ko.Spec.StartReplicationTask != nil {
		if *a.ko.Spec.StartReplicationTask != *b.ko.Spec.StartReplicationTask {
			delta.Add("Spec.StartReplicationTask", a.ko.Spec.StartReplicationTask, b.ko.Spec.StartReplicationTask)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.TableMappings, b.ko.Spec.TableMappings) {
		delta.Add("Spec.TableMappings", a.ko.Spec.TableMappings, b.ko.Spec.TableMappings)
	} else if a.ko.Spec.TableMappings != nil && b.ko.Spec.TableMappings != nil {
		if *a.ko.Spec.TableMappings != *b.ko.Spec.TableMappings {
			delta.Add("Spec.TableMappings", a.ko.Spec.TableMappings, b.ko.Spec.TableMappings)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.TargetEndpointARN, b.ko.Spec.TargetEndpointARN) {
		delta.Add("Spec.TargetEndpointARN", a.ko.Spec.TargetEndpointARN, b.ko.Spec.TargetEndpointARN)
	} else if a.ko.Spec.TargetEndpointARN != nil && b.ko.Spec.TargetEndpointARN != nil {
		if *a.ko.Spec.TargetEndpointARN != *b.ko.Spec.TargetEndpointARN {
			delta.Add("Spec.TargetEndpointARN", a.ko.Spec.TargetEndpointARN, b.ko.Spec.TargetEndpointARN)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.TargetEndpointRef, b.ko.Spec.TargetEndpointRef) {
		delta.Add("Spec.TargetEndpointRef", a.ko.Spec.TargetEndpointRef, b.ko.Spec.TargetEndpointRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.TaskData, b.ko.Spec.TaskData) {
		delta.Add("Spec.TaskData", a.ko.Spec.TaskData, b.ko.Spec.TaskData)
	} else if a.ko.Spec.TaskData != nil && b.ko.Spec.TaskData != nil {
		if *a.ko.Spec.TaskData != *b.ko.Spec.TaskData {
			delta.Add("Spec.TaskData", a.ko.Spec.TaskData, b.ko.Spec.TaskData)
		}
	}

	return delta
}
