// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package replication_task

import (
	"context"
	"fmt"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	acktypes "github.com/aws-controllers-k8s/runtime/pkg/types"

	svcapitypes "github.com/aws-controllers-k8s/dms-controller/apis/v1alpha1"
)

// ClearResolvedReferences removes any reference values that were made
// concrete in the spec. It returns a copy of the input AWSResource which
// contains the original *Ref values, but none of their respective concrete
// values.
func (rm *resourceManager) ClearResolvedReferences(res acktypes.AWSResource) acktypes.AWSResource {
	ko := rm.concreteResource(res).ko.DeepCopy()

	if ko.Spec.ReplicationInstanceRef != nil {
		ko.Spec.ReplicationInstanceARN = nil
	}

	if ko.Spec.SourceEndpointRef != nil {
		ko.Spec.SourceEndpointARN = nil
	}

	if ko.Spec.TargetEndpointRef != nil {
		ko.Spec.TargetEndpointARN = nil
	}

	return &resource{ko}
}

// ResolveReferences finds if there are any Reference field(s) present
// inside AWSResource passed in the parameter and attempts to resolve those
// reference field(s) into their respective target field(s). It returns a
// copy of the input AWSResource with resolved reference(s), a boolean which
// is set to true if the resource contains any references (regardless of if
// they are resolved successfully) and an error if the passed AWSResource's
// reference field(s) could not be resolved.
func (rm *resourceManager) ResolveReferences(
	ctx context.Context,
	apiReader client.Reader,
	res acktypes.AWSResource,
) (acktypes.AWSResource, bool, error) {
	ko := rm.concreteResource(res).ko

	resourceHasReferences := false
	err := validateReferenceFields(ko)
	if fieldHasReferences, err := rm.resolveReferenceForReplicationInstanceARN(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForSourceEndpointARN(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForTargetEndpointARN(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	return &resource{ko}, resourceHasReferences, err
}

// validateReferenceFields validates the reference field and corresponding
// identifier field.
func validateReferenceFields(ko *svcapitypes.ReplicationTask) error {

	if ko.Spec.ReplicationInstanceRef != nil && ko.Spec.ReplicationInstanceARN != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("ReplicationInstanceARN", "ReplicationInstanceRef")
	}
	if ko.Spec.ReplicationInstanceRef == nil && ko.Spec.ReplicationInstanceARN == nil {
		return ackerr.ResourceReferenceOrIDRequiredFor("ReplicationInstanceARN", "ReplicationInstanceRef")
	}

	if ko.Spec.SourceEndpointRef != nil && ko.Spec.SourceEndpointARN != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("SourceEndpointARN", "SourceEndpointRef")
	}
	if ko.Spec.SourceEndpointRef == nil && ko.Spec.SourceEndpointARN == nil {
		return ackerr.ResourceReferenceOrIDRequiredFor("SourceEndpointARN", "SourceEndpointRef")
	}

	if ko.Spec.TargetEndpointRef != nil && ko.Spec.TargetEndpointARN != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("TargetEndpointARN", "TargetEndpointRef")
	}
	if ko.Spec.TargetEndpointRef == nil && ko.Spec.TargetEndpointARN == nil {
		return ackerr.ResourceReferenceOrIDRequiredFor("TargetEndpointARN", "TargetEndpointRef")
	}
	return nil
}

// resolveReferenceForReplicationInstanceARN reads the resource referenced
// from ReplicationInstanceRef field and sets the ReplicationInstanceARN
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForReplicationInstanceARN(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.ReplicationTask,
) (hasReferences bool, err error) {
	if ko.Spec.ReplicationInstanceRef != nil && ko.Spec.ReplicationInstanceRef.From != nil {
		hasReferences = true
		arr := ko.Spec.ReplicationInstanceRef.From
		if arr.Name == nil || *arr.Name == "" {
			return hasReferences, fmt.Errorf("provided resource reference is nil or empty: ReplicationInstanceRef")
		}
		namespace := ko.ObjectMeta.GetNamespace()
		if arr.Namespace != nil && *arr.Namespace != "" {
			namespace = *arr.Namespace
		}
		obj := &svcapitypes.ReplicationInstance{}
		if err := getReferencedResourceState_ReplicationInstance(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
			return hasReferences, err
		}
		ko.Spec.ReplicationInstanceARN = (*string)(obj.Status.ACKResourceMetadata.ARN)
	}

	return hasReferences, nil
}

// getReferencedResourceState_ReplicationInstance looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_ReplicationInstance(
	ctx context.Context,
	apiReader client.Reader,
	obj *svcapitypes.ReplicationInstance,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"ReplicationInstance",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"ReplicationInstance",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"ReplicationInstance",
			namespace, name)
	}
	if obj.Status.ACKResourceMetadata == nil || obj.Status.ACKResourceMetadata.ARN == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"ReplicationInstance",
			namespace, name,
			"Status.ACKResourceMetadata.ARN")
	}
	return nil
}

// resolveReferenceForSourceEndpointARN reads the resource referenced
// from SourceEndpointRef field and sets the SourceEndpointARN
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForSourceEndpointARN(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.ReplicationTask,
) (hasReferences bool, err error) {
	if ko.Spec.SourceEndpointRef != nil && ko.Spec.SourceEndpointRef.From != nil {
		hasReferences = true
		arr := ko.Spec.SourceEndpointRef.From
		if arr.Name == nil || *arr.Name == "" {
			return hasReferences, fmt.Errorf("provided resource reference is nil or empty: SourceEndpointRef")
		}
		namespace := ko.ObjectMeta.GetNamespace()
		if arr.Namespace != nil && *arr.Namespace != "" {
			namespace = *arr.Namespace
		}
		obj := &svcapitypes.Endpoint{}
		if err := getReferencedResourceState_Endpoint(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
			return hasReferences, err
		}
		ko.Spec.SourceEndpointARN = (*string)(obj.Status.ACKResourceMetadata.ARN)
	}

	return hasReferences, nil
}

// getReferencedResourceState_Endpoint looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_Endpoint(
	ctx context.Context,
	apiReader client.Reader,
	obj *svcapitypes.Endpoint,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"Endpoint",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"Endpoint",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"Endpoint",
			namespace, name)
	}
	if obj.Status.ACKResourceMetadata == nil || obj.Status.ACKResourceMetadata.ARN == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"Endpoint",
			namespace, name,
			"Status.ACKResourceMetadata.ARN")
	}
	return nil
}

// resolveReferenceForTargetEndpointARN reads the resource referenced
// from TargetEndpointRef field and sets the TargetEndpointARN
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForTargetEndpointARN(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.ReplicationTask,
) (hasReferences bool, err error) {
	if ko.Spec.TargetEndpointRef != nil && ko.Spec.TargetEndpointRef.From != nil {
		hasReferences = true
		arr := ko.Spec.TargetEndpointRef.From
		if arr.Name == nil || *arr.Name == "" {
			return hasReferences, fmt.Errorf("provided resource reference is nil or empty: TargetEndpointRef")
		}
		namespace := ko.ObjectMeta.GetNamespace()
		if arr.Namespace != nil && *arr.Namespace != "" {
			namespace = *arr.Namespace
		}
		obj := &svcapitypes.Endpoint{}
		if err := getReferencedResourceState_Endpoint(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
			return hasReferences, err
		}
		ko.Spec.TargetEndpointARN = (*string)(obj.Status.ACKResourceMetadata.ARN)
	}

	return hasReferences, nil
}
