// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package replication_task

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"
	"time"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/databasemigrationservice"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/databasemigrationservice/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/dms-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.ReplicationTask{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}

	// sdk_read_many_post_build_request hook
	//
	// DescribeReplicationTasks does not provide any identifier input fields,
	// so we need to build a filter on our own.
	input.Filters = []svcsdktypes.Filter{
		{
			Name:   aws.String("replication-task-id"),
			Values: []string{aws.ToString(r.ko.Spec.Name)},
		},
	}

	var resp *svcsdk.DescribeReplicationTasksOutput
	resp, err = rm.sdkapi.DescribeReplicationTasks(ctx, input)

	// sdk_read_many_post_request hook
	//
	// Map ResourceNotFoundFault to NotFound error so ACK can trigger createResource
	// correctly.
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundFault" {
			rm.metrics.RecordAPICall("READ_MANY", "DescribeReplicationTasks", err)
			return nil, ackerr.NotFound
		}
	}

	rm.metrics.RecordAPICall("READ_MANY", "DescribeReplicationTasks", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "UNKNOWN" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.ReplicationTasks {
		if elem.CdcStartPosition != nil {
			ko.Spec.CdcStartPosition = elem.CdcStartPosition
		} else {
			ko.Spec.CdcStartPosition = nil
		}
		if elem.CdcStopPosition != nil {
			ko.Spec.CdcStopPosition = elem.CdcStopPosition
		} else {
			ko.Spec.CdcStopPosition = nil
		}
		if elem.LastFailureMessage != nil {
			ko.Status.LastFailureMessage = elem.LastFailureMessage
		} else {
			ko.Status.LastFailureMessage = nil
		}
		if elem.MigrationType != "" {
			ko.Spec.MigrationType = aws.String(string(elem.MigrationType))
		} else {
			ko.Spec.MigrationType = nil
		}
		if elem.RecoveryCheckpoint != nil {
			ko.Status.RecoveryCheckpoint = elem.RecoveryCheckpoint
		} else {
			ko.Status.RecoveryCheckpoint = nil
		}
		if elem.ReplicationInstanceArn != nil {
			ko.Spec.ReplicationInstanceARN = elem.ReplicationInstanceArn
		} else {
			ko.Spec.ReplicationInstanceARN = nil
		}
		if elem.ReplicationTaskArn != nil {
			if ko.Status.ACKResourceMetadata == nil {
				ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
			}
			tmpARN := ackv1alpha1.AWSResourceName(*elem.ReplicationTaskArn)
			ko.Status.ACKResourceMetadata.ARN = &tmpARN
		}
		if elem.ReplicationTaskCreationDate != nil {
			ko.Status.CreationDate = &metav1.Time{*elem.ReplicationTaskCreationDate}
		} else {
			ko.Status.CreationDate = nil
		}
		if elem.ReplicationTaskSettings != nil {
			ko.Spec.ReplicationTaskSettings = elem.ReplicationTaskSettings
		} else {
			ko.Spec.ReplicationTaskSettings = nil
		}
		if elem.ReplicationTaskStartDate != nil {
			ko.Status.StartDate = &metav1.Time{*elem.ReplicationTaskStartDate}
		} else {
			ko.Status.StartDate = nil
		}
		if elem.ReplicationTaskStats != nil {
			f11 := &svcapitypes.ReplicationTaskStats{}
			f11.ElapsedTimeMillis = &elem.ReplicationTaskStats.ElapsedTimeMillis
			if elem.ReplicationTaskStats.FreshStartDate != nil {
				f11.FreshStartDate = &metav1.Time{*elem.ReplicationTaskStats.FreshStartDate}
			}
			if elem.ReplicationTaskStats.FullLoadFinishDate != nil {
				f11.FullLoadFinishDate = &metav1.Time{*elem.ReplicationTaskStats.FullLoadFinishDate}
			}
			fullLoadProgressPercentCopy := int64(elem.ReplicationTaskStats.FullLoadProgressPercent)
			f11.FullLoadProgressPercent = &fullLoadProgressPercentCopy
			if elem.ReplicationTaskStats.FullLoadStartDate != nil {
				f11.FullLoadStartDate = &metav1.Time{*elem.ReplicationTaskStats.FullLoadStartDate}
			}
			if elem.ReplicationTaskStats.StartDate != nil {
				f11.StartDate = &metav1.Time{*elem.ReplicationTaskStats.StartDate}
			}
			if elem.ReplicationTaskStats.StopDate != nil {
				f11.StopDate = &metav1.Time{*elem.ReplicationTaskStats.StopDate}
			}
			tablesErroredCopy := int64(elem.ReplicationTaskStats.TablesErrored)
			f11.TablesErrored = &tablesErroredCopy
			tablesLoadedCopy := int64(elem.ReplicationTaskStats.TablesLoaded)
			f11.TablesLoaded = &tablesLoadedCopy
			tablesLoadingCopy := int64(elem.ReplicationTaskStats.TablesLoading)
			f11.TablesLoading = &tablesLoadingCopy
			tablesQueuedCopy := int64(elem.ReplicationTaskStats.TablesQueued)
			f11.TablesQueued = &tablesQueuedCopy
			ko.Status.Stats = f11
		} else {
			ko.Status.Stats = nil
		}
		if elem.SourceEndpointArn != nil {
			ko.Spec.SourceEndpointARN = elem.SourceEndpointArn
		} else {
			ko.Spec.SourceEndpointARN = nil
		}
		if elem.Status != nil {
			ko.Status.TaskStatus = elem.Status
		} else {
			ko.Status.TaskStatus = nil
		}
		if elem.StopReason != nil {
			ko.Status.StopReason = elem.StopReason
		} else {
			ko.Status.StopReason = nil
		}
		if elem.TableMappings != nil {
			ko.Spec.TableMappings = elem.TableMappings
		} else {
			ko.Spec.TableMappings = nil
		}
		if elem.TargetEndpointArn != nil {
			ko.Spec.TargetEndpointARN = elem.TargetEndpointArn
		} else {
			ko.Spec.TargetEndpointARN = nil
		}
		if elem.TargetReplicationInstanceArn != nil {
			ko.Status.TargetReplicationInstanceARN = elem.TargetReplicationInstanceArn
		} else {
			ko.Status.TargetReplicationInstanceARN = nil
		}
		if elem.TaskData != nil {
			ko.Spec.TaskData = elem.TaskData
		} else {
			ko.Spec.TaskData = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)

	// sdk_read_many_post_set_output hook
	//
	// Retrieves the latest tags
	if ko.Status.ACKResourceMetadata != nil && ko.Status.ACKResourceMetadata.ARN != nil {
		resourceARN := (*string)(ko.Status.ACKResourceMetadata.ARN)
		tags, err := rm.getTags(ctx, *resourceARN)
		if err != nil {
			return nil, err
		}
		ko.Spec.Tags = tags
	}

	// sdk_read_many_post_set_output hook
	//
	// Fetch connection Status and LastFailureMessage for Endpoints.
	// Clear the failure message if the connections are successful,
	// otherwise set them to the latest failure message.
	describeConnectionsInput := &svcsdk.DescribeConnectionsInput{
		Filters: []svcsdktypes.Filter{
			{
				Name: aws.String("endpoint-arn"),
				Values: []string{
					string(*ko.Spec.SourceEndpointARN),
					string(*ko.Spec.TargetEndpointARN),
				},
			},
			{
				Name:   aws.String("replication-instance-arn"),
				Values: []string{string(*ko.Spec.ReplicationInstanceARN)},
			},
		},
	}
	respDescribeConnections, err := rm.sdkapi.DescribeConnections(ctx, describeConnectionsInput)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeConnections", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundFault" {
			ackcondition.SetSynced(&resource{ko}, corev1.ConditionFalse,
				aws.String("Endpoint connections not found"), nil)
			return &resource{ko}, nil
		}
		return &resource{ko}, err
	}
	for _, elem := range respDescribeConnections.Connections {
		if *elem.EndpointArn == *ko.Spec.SourceEndpointARN {
			if elem.Status != nil {
				ko.Status.SourceEndpointConnectionStatus = elem.Status
			}
			ko.Status.SourceEndpointConnectionLastFailureMessage = elem.LastFailureMessage
		}
		if *elem.EndpointArn == *ko.Spec.TargetEndpointARN {
			if elem.Status != nil {
				ko.Status.TargetEndpointConnectionStatus = elem.Status
			}
			ko.Status.TargetEndpointConnectionLastFailureMessage = elem.LastFailureMessage
		}
	}

	// sdk_read_many_post_set_output hook
	//
	// Start the replication task if the custom StartReplicationTask field in
	// the Spec is set to true and the task is not already started and is in a
	// steady state.
	if shouldStartReplicationTask(ko) {
		if hasSteadyState(ko) {
			startReplicationTaskInput := newStartReplicationTaskRequestPayload(ko)
			_, err := rm.sdkapi.StartReplicationTask(ctx, startReplicationTaskInput)
			rm.metrics.RecordAPICall("UPDATE", "StartReplicationTask", err)
			if err != nil {
				return &resource{ko}, err
			}
			ko.Status.TaskStatus = aws.String(replicationTaskStatusStarting)
			ackcondition.SetSynced(&resource{ko}, corev1.ConditionFalse,
				aws.String("ReplicationTask entered starting state"), nil)
			return &resource{ko}, nil
		}
	}

	// sdk_read_many_post_set_output hook
	//
	// If the replication task is not in a steady state, requeue more frequently.
	if !hasSteadyState(ko) {
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionFalse,
			aws.String("ReplicationTask not in steady state"), nil)
		return &resource{ko}, nil
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return false
}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeReplicationTasksInput, error) {
	res := &svcsdk.DescribeReplicationTasksInput{}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateReplicationTaskOutput
	_ = resp
	resp, err = rm.sdkapi.CreateReplicationTask(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateReplicationTask", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.ReplicationTask.CdcStartPosition != nil {
		ko.Spec.CdcStartPosition = resp.ReplicationTask.CdcStartPosition
	} else {
		ko.Spec.CdcStartPosition = nil
	}
	if resp.ReplicationTask.CdcStopPosition != nil {
		ko.Spec.CdcStopPosition = resp.ReplicationTask.CdcStopPosition
	} else {
		ko.Spec.CdcStopPosition = nil
	}
	if resp.ReplicationTask.LastFailureMessage != nil {
		ko.Status.LastFailureMessage = resp.ReplicationTask.LastFailureMessage
	} else {
		ko.Status.LastFailureMessage = nil
	}
	if resp.ReplicationTask.MigrationType != "" {
		ko.Spec.MigrationType = aws.String(string(resp.ReplicationTask.MigrationType))
	} else {
		ko.Spec.MigrationType = nil
	}
	if resp.ReplicationTask.RecoveryCheckpoint != nil {
		ko.Status.RecoveryCheckpoint = resp.ReplicationTask.RecoveryCheckpoint
	} else {
		ko.Status.RecoveryCheckpoint = nil
	}
	if resp.ReplicationTask.ReplicationInstanceArn != nil {
		ko.Spec.ReplicationInstanceARN = resp.ReplicationTask.ReplicationInstanceArn
	} else {
		ko.Spec.ReplicationInstanceARN = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.ReplicationTask.ReplicationTaskArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.ReplicationTask.ReplicationTaskArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.ReplicationTask.ReplicationTaskCreationDate != nil {
		ko.Status.CreationDate = &metav1.Time{*resp.ReplicationTask.ReplicationTaskCreationDate}
	} else {
		ko.Status.CreationDate = nil
	}
	if resp.ReplicationTask.ReplicationTaskIdentifier != nil {
		ko.Spec.Name = resp.ReplicationTask.ReplicationTaskIdentifier
	} else {
		ko.Spec.Name = nil
	}
	if resp.ReplicationTask.ReplicationTaskSettings != nil {
		ko.Spec.ReplicationTaskSettings = resp.ReplicationTask.ReplicationTaskSettings
	} else {
		ko.Spec.ReplicationTaskSettings = nil
	}
	if resp.ReplicationTask.ReplicationTaskStartDate != nil {
		ko.Status.StartDate = &metav1.Time{*resp.ReplicationTask.ReplicationTaskStartDate}
	} else {
		ko.Status.StartDate = nil
	}
	if resp.ReplicationTask.ReplicationTaskStats != nil {
		f11 := &svcapitypes.ReplicationTaskStats{}
		f11.ElapsedTimeMillis = &resp.ReplicationTask.ReplicationTaskStats.ElapsedTimeMillis
		if resp.ReplicationTask.ReplicationTaskStats.FreshStartDate != nil {
			f11.FreshStartDate = &metav1.Time{*resp.ReplicationTask.ReplicationTaskStats.FreshStartDate}
		}
		if resp.ReplicationTask.ReplicationTaskStats.FullLoadFinishDate != nil {
			f11.FullLoadFinishDate = &metav1.Time{*resp.ReplicationTask.ReplicationTaskStats.FullLoadFinishDate}
		}
		fullLoadProgressPercentCopy := int64(resp.ReplicationTask.ReplicationTaskStats.FullLoadProgressPercent)
		f11.FullLoadProgressPercent = &fullLoadProgressPercentCopy
		if resp.ReplicationTask.ReplicationTaskStats.FullLoadStartDate != nil {
			f11.FullLoadStartDate = &metav1.Time{*resp.ReplicationTask.ReplicationTaskStats.FullLoadStartDate}
		}
		if resp.ReplicationTask.ReplicationTaskStats.StartDate != nil {
			f11.StartDate = &metav1.Time{*resp.ReplicationTask.ReplicationTaskStats.StartDate}
		}
		if resp.ReplicationTask.ReplicationTaskStats.StopDate != nil {
			f11.StopDate = &metav1.Time{*resp.ReplicationTask.ReplicationTaskStats.StopDate}
		}
		tablesErroredCopy := int64(resp.ReplicationTask.ReplicationTaskStats.TablesErrored)
		f11.TablesErrored = &tablesErroredCopy
		tablesLoadedCopy := int64(resp.ReplicationTask.ReplicationTaskStats.TablesLoaded)
		f11.TablesLoaded = &tablesLoadedCopy
		tablesLoadingCopy := int64(resp.ReplicationTask.ReplicationTaskStats.TablesLoading)
		f11.TablesLoading = &tablesLoadingCopy
		tablesQueuedCopy := int64(resp.ReplicationTask.ReplicationTaskStats.TablesQueued)
		f11.TablesQueued = &tablesQueuedCopy
		ko.Status.Stats = f11
	} else {
		ko.Status.Stats = nil
	}
	if resp.ReplicationTask.SourceEndpointArn != nil {
		ko.Spec.SourceEndpointARN = resp.ReplicationTask.SourceEndpointArn
	} else {
		ko.Spec.SourceEndpointARN = nil
	}
	if resp.ReplicationTask.Status != nil {
		ko.Status.TaskStatus = resp.ReplicationTask.Status
	} else {
		ko.Status.TaskStatus = nil
	}
	if resp.ReplicationTask.StopReason != nil {
		ko.Status.StopReason = resp.ReplicationTask.StopReason
	} else {
		ko.Status.StopReason = nil
	}
	if resp.ReplicationTask.TableMappings != nil {
		ko.Spec.TableMappings = resp.ReplicationTask.TableMappings
	} else {
		ko.Spec.TableMappings = nil
	}
	if resp.ReplicationTask.TargetEndpointArn != nil {
		ko.Spec.TargetEndpointARN = resp.ReplicationTask.TargetEndpointArn
	} else {
		ko.Spec.TargetEndpointARN = nil
	}
	if resp.ReplicationTask.TargetReplicationInstanceArn != nil {
		ko.Status.TargetReplicationInstanceARN = resp.ReplicationTask.TargetReplicationInstanceArn
	} else {
		ko.Status.TargetReplicationInstanceARN = nil
	}
	if resp.ReplicationTask.TaskData != nil {
		ko.Spec.TaskData = resp.ReplicationTask.TaskData
	} else {
		ko.Spec.TaskData = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateReplicationTaskInput, error) {
	res := &svcsdk.CreateReplicationTaskInput{}

	if r.ko.Spec.CdcStartPosition != nil {
		res.CdcStartPosition = r.ko.Spec.CdcStartPosition
	}
	if r.ko.Spec.CdcStartTime != nil {
		res.CdcStartTime = &r.ko.Spec.CdcStartTime.Time
	}
	if r.ko.Spec.CdcStopPosition != nil {
		res.CdcStopPosition = r.ko.Spec.CdcStopPosition
	}
	if r.ko.Spec.MigrationType != nil {
		res.MigrationType = svcsdktypes.MigrationTypeValue(*r.ko.Spec.MigrationType)
	}
	if r.ko.Spec.ReplicationInstanceARN != nil {
		res.ReplicationInstanceArn = r.ko.Spec.ReplicationInstanceARN
	}
	if r.ko.Spec.Name != nil {
		res.ReplicationTaskIdentifier = r.ko.Spec.Name
	}
	if r.ko.Spec.ReplicationTaskSettings != nil {
		res.ReplicationTaskSettings = r.ko.Spec.ReplicationTaskSettings
	}
	if r.ko.Spec.ResourceIdentifier != nil {
		res.ResourceIdentifier = r.ko.Spec.ResourceIdentifier
	}
	if r.ko.Spec.SourceEndpointARN != nil {
		res.SourceEndpointArn = r.ko.Spec.SourceEndpointARN
	}
	if r.ko.Spec.TableMappings != nil {
		res.TableMappings = r.ko.Spec.TableMappings
	}
	if r.ko.Spec.Tags != nil {
		f10 := []svcsdktypes.Tag{}
		for _, f10iter := range r.ko.Spec.Tags {
			f10elem := &svcsdktypes.Tag{}
			if f10iter.Key != nil {
				f10elem.Key = f10iter.Key
			}
			if f10iter.ResourceARN != nil {
				f10elem.ResourceArn = f10iter.ResourceARN
			}
			if f10iter.Value != nil {
				f10elem.Value = f10iter.Value
			}
			f10 = append(f10, *f10elem)
		}
		res.Tags = f10
	}
	if r.ko.Spec.TargetEndpointARN != nil {
		res.TargetEndpointArn = r.ko.Spec.TargetEndpointARN
	}
	if r.ko.Spec.TaskData != nil {
		res.TaskData = r.ko.Spec.TaskData
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()

	// sdk_update_pre_build_request hook
	//
	// Stop the replication task and make sure it is in a steady state
	// before updating it.
	if hasSteadyState(latest.ko) {
		if shouldStopReplicationTask(latest.ko, delta) {
			stopReplicationTaskInput := newStopReplicationTaskRequestPayload(latest.ko)
			_, err := rm.sdkapi.StopReplicationTask(ctx, stopReplicationTaskInput)
			rm.metrics.RecordAPICall("UPDATE", "StopReplicationTask", err)
			if err != nil {
				return nil, err
			}
			// Record that we stopped for an update, not by user request
			latest.ko.Status.UpdateInProgress = aws.Bool(true)
			latest.ko.Status.TaskStatus = aws.String(replicationTaskStatusStopping)
			ackcondition.SetSynced(latest, corev1.ConditionFalse,
				aws.String("ReplicationTask entered stopping state"), nil)
			return latest, nil
		}
	} else {
		ackcondition.SetSynced(latest, corev1.ConditionFalse,
			aws.String("ReplicationTask not in steady state"), nil)
		return latest, nil
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.ModifyReplicationTaskOutput
	_ = resp
	resp, err = rm.sdkapi.ModifyReplicationTask(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "ModifyReplicationTask", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	// sdk_update_pre_set_output hook
	if delta.DifferentAt("Spec.Tags") {
		if err = rm.syncTags(ctx, desired, latest); err != nil {
			return nil, err
		}
	}

	if resp.ReplicationTask.CdcStartPosition != nil {
		ko.Spec.CdcStartPosition = resp.ReplicationTask.CdcStartPosition
	} else {
		ko.Spec.CdcStartPosition = nil
	}
	if resp.ReplicationTask.CdcStopPosition != nil {
		ko.Spec.CdcStopPosition = resp.ReplicationTask.CdcStopPosition
	} else {
		ko.Spec.CdcStopPosition = nil
	}
	if resp.ReplicationTask.LastFailureMessage != nil {
		ko.Status.LastFailureMessage = resp.ReplicationTask.LastFailureMessage
	} else {
		ko.Status.LastFailureMessage = nil
	}
	if resp.ReplicationTask.MigrationType != "" {
		ko.Spec.MigrationType = aws.String(string(resp.ReplicationTask.MigrationType))
	} else {
		ko.Spec.MigrationType = nil
	}
	if resp.ReplicationTask.RecoveryCheckpoint != nil {
		ko.Status.RecoveryCheckpoint = resp.ReplicationTask.RecoveryCheckpoint
	} else {
		ko.Status.RecoveryCheckpoint = nil
	}
	if resp.ReplicationTask.ReplicationInstanceArn != nil {
		ko.Spec.ReplicationInstanceARN = resp.ReplicationTask.ReplicationInstanceArn
	} else {
		ko.Spec.ReplicationInstanceARN = nil
	}
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.ReplicationTask.ReplicationTaskArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.ReplicationTask.ReplicationTaskArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.ReplicationTask.ReplicationTaskCreationDate != nil {
		ko.Status.CreationDate = &metav1.Time{*resp.ReplicationTask.ReplicationTaskCreationDate}
	} else {
		ko.Status.CreationDate = nil
	}
	if resp.ReplicationTask.ReplicationTaskSettings != nil {
		ko.Spec.ReplicationTaskSettings = resp.ReplicationTask.ReplicationTaskSettings
	} else {
		ko.Spec.ReplicationTaskSettings = nil
	}
	if resp.ReplicationTask.ReplicationTaskStartDate != nil {
		ko.Status.StartDate = &metav1.Time{*resp.ReplicationTask.ReplicationTaskStartDate}
	} else {
		ko.Status.StartDate = nil
	}
	if resp.ReplicationTask.ReplicationTaskStats != nil {
		f11 := &svcapitypes.ReplicationTaskStats{}
		f11.ElapsedTimeMillis = &resp.ReplicationTask.ReplicationTaskStats.ElapsedTimeMillis
		if resp.ReplicationTask.ReplicationTaskStats.FreshStartDate != nil {
			f11.FreshStartDate = &metav1.Time{*resp.ReplicationTask.ReplicationTaskStats.FreshStartDate}
		}
		if resp.ReplicationTask.ReplicationTaskStats.FullLoadFinishDate != nil {
			f11.FullLoadFinishDate = &metav1.Time{*resp.ReplicationTask.ReplicationTaskStats.FullLoadFinishDate}
		}
		fullLoadProgressPercentCopy := int64(resp.ReplicationTask.ReplicationTaskStats.FullLoadProgressPercent)
		f11.FullLoadProgressPercent = &fullLoadProgressPercentCopy
		if resp.ReplicationTask.ReplicationTaskStats.FullLoadStartDate != nil {
			f11.FullLoadStartDate = &metav1.Time{*resp.ReplicationTask.ReplicationTaskStats.FullLoadStartDate}
		}
		if resp.ReplicationTask.ReplicationTaskStats.StartDate != nil {
			f11.StartDate = &metav1.Time{*resp.ReplicationTask.ReplicationTaskStats.StartDate}
		}
		if resp.ReplicationTask.ReplicationTaskStats.StopDate != nil {
			f11.StopDate = &metav1.Time{*resp.ReplicationTask.ReplicationTaskStats.StopDate}
		}
		tablesErroredCopy := int64(resp.ReplicationTask.ReplicationTaskStats.TablesErrored)
		f11.TablesErrored = &tablesErroredCopy
		tablesLoadedCopy := int64(resp.ReplicationTask.ReplicationTaskStats.TablesLoaded)
		f11.TablesLoaded = &tablesLoadedCopy
		tablesLoadingCopy := int64(resp.ReplicationTask.ReplicationTaskStats.TablesLoading)
		f11.TablesLoading = &tablesLoadingCopy
		tablesQueuedCopy := int64(resp.ReplicationTask.ReplicationTaskStats.TablesQueued)
		f11.TablesQueued = &tablesQueuedCopy
		ko.Status.Stats = f11
	} else {
		ko.Status.Stats = nil
	}
	if resp.ReplicationTask.SourceEndpointArn != nil {
		ko.Spec.SourceEndpointARN = resp.ReplicationTask.SourceEndpointArn
	} else {
		ko.Spec.SourceEndpointARN = nil
	}
	if resp.ReplicationTask.Status != nil {
		ko.Status.TaskStatus = resp.ReplicationTask.Status
	} else {
		ko.Status.TaskStatus = nil
	}
	if resp.ReplicationTask.StopReason != nil {
		ko.Status.StopReason = resp.ReplicationTask.StopReason
	} else {
		ko.Status.StopReason = nil
	}
	if resp.ReplicationTask.TableMappings != nil {
		ko.Spec.TableMappings = resp.ReplicationTask.TableMappings
	} else {
		ko.Spec.TableMappings = nil
	}
	if resp.ReplicationTask.TargetEndpointArn != nil {
		ko.Spec.TargetEndpointARN = resp.ReplicationTask.TargetEndpointArn
	} else {
		ko.Spec.TargetEndpointARN = nil
	}
	if resp.ReplicationTask.TargetReplicationInstanceArn != nil {
		ko.Status.TargetReplicationInstanceARN = resp.ReplicationTask.TargetReplicationInstanceArn
	} else {
		ko.Status.TargetReplicationInstanceARN = nil
	}
	if resp.ReplicationTask.TaskData != nil {
		ko.Spec.TaskData = resp.ReplicationTask.TaskData
	} else {
		ko.Spec.TaskData = nil
	}

	rm.setStatusDefaults(ko)

	// sdk_update_post_set_output hook
	//
	// Reset Status.UpdateInProgress so the next sync can start the
	// task again if needed.
	ko.Status.UpdateInProgress = nil

	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.ModifyReplicationTaskInput, error) {
	res := &svcsdk.ModifyReplicationTaskInput{}

	if r.ko.Spec.CdcStartPosition != nil {
		res.CdcStartPosition = r.ko.Spec.CdcStartPosition
	}
	if r.ko.Spec.CdcStartTime != nil {
		res.CdcStartTime = &r.ko.Spec.CdcStartTime.Time
	}
	if r.ko.Spec.CdcStopPosition != nil {
		res.CdcStopPosition = r.ko.Spec.CdcStopPosition
	}
	if r.ko.Spec.MigrationType != nil {
		res.MigrationType = svcsdktypes.MigrationTypeValue(*r.ko.Spec.MigrationType)
	}
	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.ReplicationTaskArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}
	if r.ko.Spec.ReplicationTaskSettings != nil {
		res.ReplicationTaskSettings = r.ko.Spec.ReplicationTaskSettings
	}
	if r.ko.Spec.TableMappings != nil {
		res.TableMappings = r.ko.Spec.TableMappings
	}
	if r.ko.Spec.TaskData != nil {
		res.TaskData = r.ko.Spec.TaskData
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()

	// sdk_delete_pre_build_request hook
	//
	// Stop the replication task and make sure it is in a steady state
	// before deleting it.
	if hasSteadyState(r.ko) {
		if shouldStopReplicationTask(r.ko, nil) {
			stopReplicationTaskInput := newStopReplicationTaskRequestPayload(r.ko)
			_, err := rm.sdkapi.StopReplicationTask(ctx, stopReplicationTaskInput)
			rm.metrics.RecordAPICall("UPDATE", "StopReplicationTask", err)
			if err != nil {
				return nil, err
			}
			r.ko.Status.TaskStatus = aws.String(replicationTaskStatusStopping)
			return r, ackrequeue.NeededAfter(errors.New("ReplicationTask entered stopping state"), 10*time.Second)
		}
	} else {
		return r, ackrequeue.NeededAfter(errors.New("ReplicationTask not in steady state"), 10*time.Second)
	}

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteReplicationTaskOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteReplicationTask(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteReplicationTask", err)

	// sdk_delete_post_request hook
	//
	// Wait for the replication task to be deleted before setResourceUnmanaged.
	if err != nil {
		return nil, err
	}
	r.ko.Status.TaskStatus = aws.String(replicationTaskStatusDeleting)
	return r, ackrequeue.NeededAfter(errors.New("Waiting for ReplicationTask deletion to complete"), 10*time.Second)

	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteReplicationTaskInput, error) {
	res := &svcsdk.DeleteReplicationTaskInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.ReplicationTaskArn = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.ReplicationTask,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	if syncCondition == nil && onSuccess {
		syncCondition = &ackv1alpha1.Condition{
			Type:   ackv1alpha1.ConditionTypeResourceSynced,
			Status: corev1.ConditionTrue,
		}
		ko.Status.Conditions = append(ko.Status.Conditions, syncCondition)
	}
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "InvalidParameterCombinationException":
		return true
	default:
		return false
	}
}
