// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CertificateSpec defines the desired state of Certificate.
//
// The SSL certificate that can be used to encrypt connections between the endpoints
// and the replication instance.
type CertificateSpec struct {

	// The contents of a .pem file, which contains an X.509 certificate.
	CertificatePem *ackv1alpha1.SecretKeyReference `json:"certificatePem,omitempty"`
	// A Base64 encoded Oracle Wallet certificate (cwallet.sso) for use with SSL.
	CertificateWallet *ackv1alpha1.SecretKeyReference `json:"certificateWallet,omitempty"`
	// An KMS key identifier that is used to encrypt the certificate.
	//
	// If you don't specify a value for the KmsKeyId parameter, then DMS uses your
	// default encryption key.
	//
	// KMS creates the default encryption key for your Amazon Web Services account.
	// Your Amazon Web Services account has a different default encryption key for
	// each Amazon Web Services Region.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	KMSKeyID  *string                                  `json:"kmsKeyID,omitempty"`
	KMSKeyRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"kmsKeyRef,omitempty"`
	// A customer-assigned name for the certificate. Identifiers must begin with
	// a letter and must contain only ASCII letters, digits, and hyphens. They can't
	// end with a hyphen or contain two consecutive hyphens.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The tags associated with the certificate.
	Tags []*Tag `json:"tags,omitempty"`
}

// CertificateStatus defines the observed state of Certificate
type CertificateStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The date that the certificate was created.
	// +kubebuilder:validation:Optional
	CertificateCreationDate *metav1.Time `json:"certificateCreationDate,omitempty"`
	// The owner of the certificate.
	// +kubebuilder:validation:Optional
	CertificateOwner *string `json:"certificateOwner,omitempty"`
	// The key length of the cryptographic algorithm being used.
	// +kubebuilder:validation:Optional
	KeyLength *int64 `json:"keyLength,omitempty"`
	// The signing algorithm for the certificate.
	// +kubebuilder:validation:Optional
	SigningAlgorithm *string `json:"signingAlgorithm,omitempty"`
	// The beginning date that the certificate is valid.
	// +kubebuilder:validation:Optional
	ValidFromDate *metav1.Time `json:"validFromDate,omitempty"`
	// The final date that the certificate is valid.
	// +kubebuilder:validation:Optional
	ValidToDate *metav1.Time `json:"validToDate,omitempty"`
}

// Certificate is the Schema for the Certificates API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Synced",type="string",priority=0,JSONPath=".status.conditions[?(@.type==\"ACK.ResourceSynced\")].status"
// +kubebuilder:printcolumn:name="Age",type="date",priority=0,JSONPath=".metadata.creationTimestamp"
type Certificate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CertificateSpec   `json:"spec,omitempty"`
	Status            CertificateStatus `json:"status,omitempty"`
}

// CertificateList contains a list of Certificate
// +kubebuilder:object:root=true
type CertificateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Certificate `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Certificate{}, &CertificateList{})
}
