// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type AssessmentReportType string

const (
	AssessmentReportType_csv AssessmentReportType = "csv"
	AssessmentReportType_pdf AssessmentReportType = "pdf"
)

type AuthMechanismValue string

const (
	AuthMechanismValue_default     AuthMechanismValue = "default"
	AuthMechanismValue_mongodb_cr  AuthMechanismValue = "mongodb_cr"
	AuthMechanismValue_scram_sha_1 AuthMechanismValue = "scram_sha_1"
)

type AuthTypeValue string

const (
	AuthTypeValue_no       AuthTypeValue = "no"
	AuthTypeValue_password AuthTypeValue = "password"
)

type CannedACLForObjectsValue string

const (
	CannedACLForObjectsValue_authenticated_read        CannedACLForObjectsValue = "authenticated-read"
	CannedACLForObjectsValue_aws_exec_read             CannedACLForObjectsValue = "aws-exec-read"
	CannedACLForObjectsValue_bucket_owner_full_control CannedACLForObjectsValue = "bucket-owner-full-control"
	CannedACLForObjectsValue_bucket_owner_read         CannedACLForObjectsValue = "bucket-owner-read"
	CannedACLForObjectsValue_none                      CannedACLForObjectsValue = "none"
	CannedACLForObjectsValue_private                   CannedACLForObjectsValue = "private"
	CannedACLForObjectsValue_public_read               CannedACLForObjectsValue = "public-read"
	CannedACLForObjectsValue_public_read_write         CannedACLForObjectsValue = "public-read-write"
)

type CharLengthSemantics string

const (
	CharLengthSemantics_byte    CharLengthSemantics = "byte"
	CharLengthSemantics_char    CharLengthSemantics = "char"
	CharLengthSemantics_default CharLengthSemantics = "default"
)

type CollectorStatus string

const (
	CollectorStatus_ACTIVE       CollectorStatus = "ACTIVE"
	CollectorStatus_UNREGISTERED CollectorStatus = "UNREGISTERED"
)

type CompressionTypeValue string

const (
	CompressionTypeValue_gzip CompressionTypeValue = "gzip"
	CompressionTypeValue_none CompressionTypeValue = "none"
)

type DataFormatValue string

const (
	DataFormatValue_csv     DataFormatValue = "csv"
	DataFormatValue_parquet DataFormatValue = "parquet"
)

type DatabaseMode string

const (
	DatabaseMode_babelfish DatabaseMode = "babelfish"
	DatabaseMode_default   DatabaseMode = "default"
)

type DatePartitionDelimiterValue string

const (
	DatePartitionDelimiterValue_DASH       DatePartitionDelimiterValue = "DASH"
	DatePartitionDelimiterValue_NONE       DatePartitionDelimiterValue = "NONE"
	DatePartitionDelimiterValue_SLASH      DatePartitionDelimiterValue = "SLASH"
	DatePartitionDelimiterValue_UNDERSCORE DatePartitionDelimiterValue = "UNDERSCORE"
)

type DatePartitionSequenceValue string

const (
	DatePartitionSequenceValue_DDMMYYYY   DatePartitionSequenceValue = "DDMMYYYY"
	DatePartitionSequenceValue_MMYYYYDD   DatePartitionSequenceValue = "MMYYYYDD"
	DatePartitionSequenceValue_YYYYMM     DatePartitionSequenceValue = "YYYYMM"
	DatePartitionSequenceValue_YYYYMMDD   DatePartitionSequenceValue = "YYYYMMDD"
	DatePartitionSequenceValue_YYYYMMDDHH DatePartitionSequenceValue = "YYYYMMDDHH"
)

type DmsSSLModeValue string

const (
	DmsSSLModeValue_none        DmsSSLModeValue = "none"
	DmsSSLModeValue_require     DmsSSLModeValue = "require"
	DmsSSLModeValue_verify_ca   DmsSSLModeValue = "verify-ca"
	DmsSSLModeValue_verify_full DmsSSLModeValue = "verify-full"
)

type EncodingTypeValue string

const (
	EncodingTypeValue_plain            EncodingTypeValue = "plain"
	EncodingTypeValue_plain_dictionary EncodingTypeValue = "plain-dictionary"
	EncodingTypeValue_rle_dictionary   EncodingTypeValue = "rle-dictionary"
)

type EncryptionModeValue string

const (
	EncryptionModeValue_sse_kms EncryptionModeValue = "sse-kms"
	EncryptionModeValue_sse_s3  EncryptionModeValue = "sse-s3"
)

type EndpointSettingTypeValue string

const (
	EndpointSettingTypeValue_boolean EndpointSettingTypeValue = "boolean"
	EndpointSettingTypeValue_enum    EndpointSettingTypeValue = "enum"
	EndpointSettingTypeValue_integer EndpointSettingTypeValue = "integer"
	EndpointSettingTypeValue_string  EndpointSettingTypeValue = "string"
)

type KafkaSASLMechanism string

const (
	KafkaSASLMechanism_plain         KafkaSASLMechanism = "plain"
	KafkaSASLMechanism_scram_sha_512 KafkaSASLMechanism = "scram-sha-512"
)

type KafkaSSLEndpointIDentificationAlgorithm string

const (
	KafkaSSLEndpointIDentificationAlgorithm_https KafkaSSLEndpointIDentificationAlgorithm = "https"
	KafkaSSLEndpointIDentificationAlgorithm_none  KafkaSSLEndpointIDentificationAlgorithm = "none"
)

type KafkaSecurityProtocol string

const (
	KafkaSecurityProtocol_plaintext          KafkaSecurityProtocol = "plaintext"
	KafkaSecurityProtocol_sasl_ssl           KafkaSecurityProtocol = "sasl-ssl"
	KafkaSecurityProtocol_ssl_authentication KafkaSecurityProtocol = "ssl-authentication"
	KafkaSecurityProtocol_ssl_encryption     KafkaSecurityProtocol = "ssl-encryption"
)

type LongVarcharMappingType string

const (
	LongVarcharMappingType_clob    LongVarcharMappingType = "clob"
	LongVarcharMappingType_nclob   LongVarcharMappingType = "nclob"
	LongVarcharMappingType_wstring LongVarcharMappingType = "wstring"
)

type MessageFormatValue string

const (
	MessageFormatValue_json             MessageFormatValue = "json"
	MessageFormatValue_json_unformatted MessageFormatValue = "json-unformatted"
)

type MigrationTypeValue string

const (
	MigrationTypeValue_cdc               MigrationTypeValue = "cdc"
	MigrationTypeValue_full_load         MigrationTypeValue = "full-load"
	MigrationTypeValue_full_load_and_cdc MigrationTypeValue = "full-load-and-cdc"
)

type MySQLAuthenticationMethod string

const (
	MySQLAuthenticationMethod_iam      MySQLAuthenticationMethod = "iam"
	MySQLAuthenticationMethod_password MySQLAuthenticationMethod = "password"
)

type NestingLevelValue string

const (
	NestingLevelValue_none NestingLevelValue = "none"
	NestingLevelValue_one  NestingLevelValue = "one"
)

type OracleAuthenticationMethod string

const (
	OracleAuthenticationMethod_kerberos OracleAuthenticationMethod = "kerberos"
	OracleAuthenticationMethod_password OracleAuthenticationMethod = "password"
)

type OriginTypeValue string

const (
	OriginTypeValue_SOURCE OriginTypeValue = "SOURCE"
	OriginTypeValue_TARGET OriginTypeValue = "TARGET"
)

type ParquetVersionValue string

const (
	ParquetVersionValue_parquet_1_0 ParquetVersionValue = "parquet-1-0"
	ParquetVersionValue_parquet_2_0 ParquetVersionValue = "parquet-2-0"
)

type PluginNameValue string

const (
	PluginNameValue_no_preference PluginNameValue = "no-preference"
	PluginNameValue_pglogical     PluginNameValue = "pglogical"
	PluginNameValue_test_decoding PluginNameValue = "test-decoding"
)

type PostgreSQLAuthenticationMethod string

const (
	PostgreSQLAuthenticationMethod_iam      PostgreSQLAuthenticationMethod = "iam"
	PostgreSQLAuthenticationMethod_password PostgreSQLAuthenticationMethod = "password"
)

type RedisAuthTypeValue string

const (
	RedisAuthTypeValue_auth_role  RedisAuthTypeValue = "auth-role"
	RedisAuthTypeValue_auth_token RedisAuthTypeValue = "auth-token"
	RedisAuthTypeValue_none       RedisAuthTypeValue = "none"
)

type RefreshSchemasStatusTypeValue string

const (
	RefreshSchemasStatusTypeValue_failed     RefreshSchemasStatusTypeValue = "failed"
	RefreshSchemasStatusTypeValue_refreshing RefreshSchemasStatusTypeValue = "refreshing"
	RefreshSchemasStatusTypeValue_successful RefreshSchemasStatusTypeValue = "successful"
)

type ReleaseStatusValues string

const (
	ReleaseStatusValues_beta ReleaseStatusValues = "beta"
	ReleaseStatusValues_prod ReleaseStatusValues = "prod"
)

type ReloadOptionValue string

const (
	ReloadOptionValue_data_reload   ReloadOptionValue = "data-reload"
	ReloadOptionValue_validate_only ReloadOptionValue = "validate-only"
)

type ReplicationEndpointTypeValue string

const (
	ReplicationEndpointTypeValue_source ReplicationEndpointTypeValue = "source"
	ReplicationEndpointTypeValue_target ReplicationEndpointTypeValue = "target"
)

type SQLServerAuthenticationMethod string

const (
	SQLServerAuthenticationMethod_kerberos SQLServerAuthenticationMethod = "kerberos"
	SQLServerAuthenticationMethod_password SQLServerAuthenticationMethod = "password"
)

type SSLSecurityProtocolValue string

const (
	SSLSecurityProtocolValue_plaintext      SSLSecurityProtocolValue = "plaintext"
	SSLSecurityProtocolValue_ssl_encryption SSLSecurityProtocolValue = "ssl-encryption"
)

type SafeguardPolicy string

const (
	SafeguardPolicy_exclusive_automatic_truncation       SafeguardPolicy = "exclusive-automatic-truncation"
	SafeguardPolicy_rely_on_sql_server_replication_agent SafeguardPolicy = "rely-on-sql-server-replication-agent"
	SafeguardPolicy_shared_automatic_truncation          SafeguardPolicy = "shared-automatic-truncation"
)

type SourceType string

const (
	SourceType_replication_instance SourceType = "replication-instance"
)

type StartReplicationMigrationTypeValue string

const (
	StartReplicationMigrationTypeValue_reload_target     StartReplicationMigrationTypeValue = "reload-target"
	StartReplicationMigrationTypeValue_resume_processing StartReplicationMigrationTypeValue = "resume-processing"
	StartReplicationMigrationTypeValue_start_replication StartReplicationMigrationTypeValue = "start-replication"
)

type StartReplicationTaskTypeValue string

const (
	StartReplicationTaskTypeValue_reload_target     StartReplicationTaskTypeValue = "reload-target"
	StartReplicationTaskTypeValue_resume_processing StartReplicationTaskTypeValue = "resume-processing"
	StartReplicationTaskTypeValue_start_replication StartReplicationTaskTypeValue = "start-replication"
)

type TablePreparationMode string

const (
	TablePreparationMode_do_nothing            TablePreparationMode = "do-nothing"
	TablePreparationMode_drop_tables_on_target TablePreparationMode = "drop-tables-on-target"
	TablePreparationMode_truncate              TablePreparationMode = "truncate"
)

type TargetDBType string

const (
	TargetDBType_multiple_databases TargetDBType = "multiple-databases"
	TargetDBType_specific_database  TargetDBType = "specific-database"
)

type TlogAccessMode string

const (
	TlogAccessMode_BackupOnly   TlogAccessMode = "BackupOnly"
	TlogAccessMode_PreferBackup TlogAccessMode = "PreferBackup"
	TlogAccessMode_PreferTlog   TlogAccessMode = "PreferTlog"
	TlogAccessMode_TlogOnly     TlogAccessMode = "TlogOnly"
)

type VersionStatus string

const (
	VersionStatus_OUTDATED    VersionStatus = "OUTDATED"
	VersionStatus_UNSUPPORTED VersionStatus = "UNSUPPORTED"
	VersionStatus_UP_TO_DATE  VersionStatus = "UP_TO_DATE"
)
