// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EventSubscriptionSpec defines the desired state of EventSubscription.
//
// Describes an event notification subscription created by the CreateEventSubscription
// operation.
type EventSubscriptionSpec struct {

	// A Boolean value; set to true to activate the subscription, or set to false
	// to create the subscription but not activate it.
	Enabled *bool `json:"enabled,omitempty"`
	// A list of event categories for a source type that you want to subscribe to.
	// For more information, see Working with Events and Notifications (https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Events.html)
	// in the Database Migration Service User Guide.
	EventCategories []*string `json:"eventCategories,omitempty"`
	// The name of the DMS event notification subscription. This name must be less
	// than 255 characters.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The Amazon Resource Name (ARN) of the Amazon SNS topic created for event
	// notification. The ARN is created by Amazon SNS when you create a topic and
	// subscribe to it.
	SNSTopicARN *string `json:"snsTopicARN,omitempty"`
	// Reference to an ACK managed Amazon SNS topic resource created for event
	// notification.
	SNSTopicRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"snsTopicRef,omitempty"`
	// A list of identifiers for which DMS provides notification events.
	//
	// If you don't specify a value, notifications are provided for all sources.
	//
	// If you specify multiple values, they must be of the same type. For example,
	// if you specify a database instance ID, then all of the other values must
	// be database instance IDs.
	SourceIDs []*string `json:"sourceIDs,omitempty"`
	// The type of DMS resource that generates the events. For example, if you want
	// to be notified of events generated by a replication instance, you set this
	// parameter to replication-instance. If this value isn't specified, all events
	// are returned.
	//
	// Valid values: replication-instance | replication-task
	SourceType *string `json:"sourceType,omitempty"`
	// One or more tags to be assigned to the event subscription.
	Tags []*Tag `json:"tags,omitempty"`
}

// EventSubscriptionStatus defines the observed state of EventSubscription
type EventSubscriptionStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The DMS event notification subscription Id.
	// +kubebuilder:validation:Optional
	CustSubscriptionID *string `json:"custSubscriptionID,omitempty"`
	// The Amazon Web Services customer account associated with the DMS event notification
	// subscription.
	// +kubebuilder:validation:Optional
	CustomerAWSID *string `json:"customerAWSID,omitempty"`
	// The time the DMS event notification subscription was created.
	// +kubebuilder:validation:Optional
	SubscriptionCreationTime *string `json:"subscriptionCreationTime,omitempty"`
	// The status of the DMS event notification subscription.
	//
	// Constraints:
	//
	// Can be one of the following: creating | modifying | deleting | active | no-permission
	// | topic-not-exist
	//
	// The status "no-permission" indicates that DMS no longer has permission to
	// post to the SNS topic. The status "topic-not-exist" indicates that the topic
	// was deleted after the subscription was created.
	// +kubebuilder:validation:Optional
	SubscriptionStatus *string `json:"subscriptionStatus,omitempty"`
}

// EventSubscription is the Schema for the EventSubscriptions API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type=string,priority=0,JSONPath=`.status.subscriptionStatus`
// +kubebuilder:printcolumn:name="Synced",type="string",priority=0,JSONPath=".status.conditions[?(@.type==\"ACK.ResourceSynced\")].status"
// +kubebuilder:printcolumn:name="Age",type="date",priority=0,JSONPath=".metadata.creationTimestamp"
type EventSubscription struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              EventSubscriptionSpec   `json:"spec,omitempty"`
	Status            EventSubscriptionStatus `json:"status,omitempty"`
}

// EventSubscriptionList contains a list of EventSubscription
// +kubebuilder:object:root=true
type EventSubscriptionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EventSubscription `json:"items"`
}

func init() {
	SchemeBuilder.Register(&EventSubscription{}, &EventSubscriptionList{})
}
