// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ReplicationSubnetGroupSpec defines the desired state of ReplicationSubnetGroup.
//
// Describes a subnet group in response to a request by the DescribeReplicationSubnetGroups
// operation.
type ReplicationSubnetGroupSpec struct {

	// The description for the subnet group.
	//
	// Constraints: This parameter Must not contain non-printable control characters.
	// +kubebuilder:validation:Required
	Description *string `json:"description"`
	// The name for the replication subnet group. This value is stored as a lowercase
	// string.
	//
	// Constraints: Must contain no more than 255 alphanumeric characters, periods,
	// underscores, or hyphens. Must not be "default".
	//
	// Example: mySubnetgroup
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// Two or more subnet IDs to be assigned to the subnet group.
	// +kubebuilder:validation:Required
	SubnetIDs []*string `json:"subnetIDs"`
	// One or more tags to be assigned to the subnet group.
	Tags []*Tag `json:"tags,omitempty"`
}

// ReplicationSubnetGroupStatus defines the observed state of ReplicationSubnetGroup
type ReplicationSubnetGroupStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// Indicates whether the replication subnet group is read-only. When set to
	// true, this subnet group is managed by DMS as part of a zero-ETL integration
	// and cannot be modified or deleted directly. You can only modify or delete
	// read-only subnet groups through their associated zero-ETL integration.
	// +kubebuilder:validation:Optional
	IsReadOnly *bool `json:"isReadOnly,omitempty"`
	// The status of the subnet group.
	// +kubebuilder:validation:Optional
	SubnetGroupStatus *string `json:"subnetGroupStatus,omitempty"`
	// The subnets that are in the subnet group.
	// +kubebuilder:validation:Optional
	Subnets []*Subnet `json:"subnets,omitempty"`
	// The IP addressing protocol supported by the subnet group. This is used by
	// a replication instance with values such as IPv4 only or Dual-stack that supports
	// both IPv4 and IPv6 addressing. IPv6 only is not yet supported.
	// +kubebuilder:validation:Optional
	SupportedNetworkTypes []*string `json:"supportedNetworkTypes,omitempty"`
	// The ID of the VPC.
	// +kubebuilder:validation:Optional
	VPCID *string `json:"vpcID,omitempty"`
}

// ReplicationSubnetGroup is the Schema for the ReplicationSubnetGroups API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type=string,priority=0,JSONPath=`.status.subnetGroupStatus`
// +kubebuilder:printcolumn:name="Synced",type="string",priority=0,JSONPath=".status.conditions[?(@.type==\"ACK.ResourceSynced\")].status"
// +kubebuilder:printcolumn:name="Age",type="date",priority=0,JSONPath=".metadata.creationTimestamp"
type ReplicationSubnetGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ReplicationSubnetGroupSpec   `json:"spec,omitempty"`
	Status            ReplicationSubnetGroupStatus `json:"status,omitempty"`
}

// ReplicationSubnetGroupList contains a list of ReplicationSubnetGroup
// +kubebuilder:object:root=true
type ReplicationSubnetGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ReplicationSubnetGroup `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ReplicationSubnetGroup{}, &ReplicationSubnetGroupList{})
}
