// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ReplicationInstanceSpec defines the desired state of ReplicationInstance.
//
// Provides information that defines a replication instance.
type ReplicationInstanceSpec struct {

	// The amount of storage (in gigabytes) to be initially allocated for the replication
	// instance.
	AllocatedStorage *int64 `json:"allocatedStorage,omitempty"`
	// A value that indicates whether minor engine upgrades are applied automatically
	// to the replication instance during the maintenance window. This parameter
	// defaults to true.
	//
	// Default: true
	AutoMinorVersionUpgrade *bool `json:"autoMinorVersionUpgrade,omitempty"`
	// The Availability Zone where the replication instance will be created. The
	// default value is a random, system-chosen Availability Zone in the endpoint's
	// Amazon Web Services Region, for example: us-east-1d.
	AvailabilityZone *string `json:"availabilityZone,omitempty"`
	// A list of custom DNS name servers supported for the replication instance
	// to access your on-premise source or target database. This list overrides
	// the default name servers supported by the replication instance. You can specify
	// a comma-separated list of internet addresses for up to four on-premise DNS
	// name servers. For example: "1.1.1.1,2.2.2.2,3.3.3.3,4.4.4.4"
	DNSNameServers *string `json:"dnsNameServers,omitempty"`
	// The engine version number of the replication instance.
	//
	// If an engine version number is not specified when a replication instance
	// is created, the default is the latest engine version available.
	EngineVersion *string `json:"engineVersion,omitempty"`
	// The compute and memory capacity of the replication instance as defined for
	// the specified replication instance class. For example to specify the instance
	// class dms.c4.large, set this parameter to "dms.c4.large".
	//
	// For more information on the settings and capacities for the available replication
	// instance classes, see Choosing the right DMS replication instance (https://docs.aws.amazon.com/dms/latest/userguide/CHAP_ReplicationInstance.Types.html);
	// and, Selecting the best size for a replication instance (https://docs.aws.amazon.com/dms/latest/userguide/CHAP_BestPractices.SizingReplicationInstance.html).
	// +kubebuilder:validation:Required
	InstanceClass *string `json:"instanceClass"`
	// Specifies the settings required for kerberos authentication when creating
	// the replication instance.
	KerberosAuthenticationSettings *KerberosAuthenticationSettings `json:"kerberosAuthenticationSettings,omitempty"`
	// An KMS key identifier that is used to encrypt the data on the replication
	// instance.
	//
	// If you don't specify a value for the KmsKeyId parameter, then DMS uses your
	// default encryption key.
	//
	// KMS creates the default encryption key for your Amazon Web Services account.
	// Your Amazon Web Services account has a different default encryption key for
	// each Amazon Web Services Region.
	KMSKeyID *string `json:"kmsKeyID,omitempty"`
	// Reference to an ACK managed KMS key that is used to encrypt the data on the
	// replication instance.
	KMSKeyRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"kmsKeyRef,omitempty"`
	// Specifies whether the replication instance is a Multi-AZ deployment. You
	// can't set the AvailabilityZone parameter if the Multi-AZ parameter is set
	// to true.
	MultiAZ *bool `json:"multiAZ,omitempty"`
	// The replication instance identifier. This parameter is stored as a lowercase
	// string.
	//
	// Constraints:
	//
	//   - Must contain 1-63 alphanumeric characters or hyphens.
	//
	//   - First character must be a letter.
	//
	//   - Can't end with a hyphen or contain two consecutive hyphens.
	//
	// Example: myrepinstance
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The type of IP address protocol used by a replication instance, such as IPv4
	// only or Dual-stack that supports both IPv4 and IPv6 addressing. IPv6 only
	// is not yet supported.
	NetworkType *string `json:"networkType,omitempty"`
	// The weekly time range during which system maintenance can occur, in Universal
	// Coordinated Time (UTC).
	//
	// Format: ddd:hh24:mi-ddd:hh24:mi
	//
	// Default: A 30-minute window selected at random from an 8-hour block of time
	// per Amazon Web Services Region, occurring on a random day of the week.
	//
	// Valid Days: Mon, Tue, Wed, Thu, Fri, Sat, Sun
	//
	// Constraints: Minimum 30-minute window.
	PreferredMaintenanceWindow *string `json:"preferredMaintenanceWindow,omitempty"`
	// Specifies the accessibility options for the replication instance. A value
	// of true represents an instance with a public IP address. A value of false
	// represents an instance with a private IP address. The default value is true.
	PubliclyAccessible *bool `json:"publiclyAccessible,omitempty"`
	// A friendly name for the resource identifier at the end of the EndpointArn
	// response parameter that is returned in the created Endpoint object. The value
	// for this parameter can have up to 31 characters. It can contain only ASCII
	// letters, digits, and hyphen ('-'). Also, it can't end with a hyphen or contain
	// two consecutive hyphens, and can only begin with a letter, such as Example-App-ARN1.
	// For example, this value might result in the EndpointArn value arn:aws:dms:eu-west-1:012345678901:rep:Example-App-ARN1.
	// If you don't specify a ResourceIdentifier value, DMS generates a default
	// identifier value for the end of EndpointArn.
	ResourceIdentifier *string `json:"resourceIdentifier,omitempty"`
	// Specifies the VPC security group to be used with the replication instance.
	// The VPC security group must work with the VPC containing the replication
	// instance.
	SecurityGroupIDs []*string `json:"securityGroupIDs,omitempty"`
	// One or more references to ACK managed EC2 security group resources to be
	// used with the replication instance.
	// The security group must work with the VPC containing the replication
	// instance.
	SecurityGroupRefs []*ackv1alpha1.AWSResourceReferenceWrapper `json:"securityGroupRefs,omitempty"`
	// A subnet group to associate with the replication instance.
	SubnetGroupID *string `json:"subnetGroupID,omitempty"`
	// Reference to an ACK managed replication subnet group to associate with this
	// replication instance.
	SubnetGroupRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"subnetGroupRef,omitempty"`
	// One or more tags to be assigned to the replication instance.
	Tags []*Tag `json:"tags,omitempty"`
}

// ReplicationInstanceStatus defines the observed state of ReplicationInstance
type ReplicationInstanceStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The expiration date of the free replication instance that is part of the
	// Free DMS program.
	// +kubebuilder:validation:Optional
	FreeUntil *metav1.Time `json:"freeUntil,omitempty"`
	// One or more IPv6 addresses for the replication instance.
	// +kubebuilder:validation:Optional
	IPv6Addresses []*string `json:"ipv6Addresses,omitempty"`
	// The time the replication instance was created.
	// +kubebuilder:validation:Optional
	InstanceCreateTime *metav1.Time `json:"instanceCreateTime,omitempty"`
	// The status of the replication instance. The possible return values include:
	//
	//    * "available"
	//
	//    * "creating"
	//
	//    * "deleted"
	//
	//    * "deleting"
	//
	//    * "failed"
	//
	//    * "modifying"
	//
	//    * "upgrading"
	//
	//    * "rebooting"
	//
	//    * "resetting-master-credentials"
	//
	//    * "storage-full"
	//
	//    * "incompatible-credentials"
	//
	//    * "incompatible-network"
	//
	//    * "maintenance"
	// +kubebuilder:validation:Optional
	InstanceStatus *string `json:"instanceStatus,omitempty"`
	// The pending modification values.
	// +kubebuilder:validation:Optional
	PendingModifiedValues *ReplicationPendingModifiedValues `json:"pendingModifiedValues,omitempty"`
	// The private IP address of the replication instance.
	// +kubebuilder:validation:Optional
	PrivateIPAddress *string `json:"privateIPAddress,omitempty"`
	// One or more private IP addresses for the replication instance.
	// +kubebuilder:validation:Optional
	PrivateIPAddresses []*string `json:"privateIPAddresses,omitempty"`
	// The public IP address of the replication instance.
	// +kubebuilder:validation:Optional
	PublicIPAddress *string `json:"publicIPAddress,omitempty"`
	// One or more public IP addresses for the replication instance.
	// +kubebuilder:validation:Optional
	PublicIPAddresses []*string `json:"publicIPAddresses,omitempty"`
	// The Availability Zone of the standby replication instance in a Multi-AZ deployment.
	// +kubebuilder:validation:Optional
	SecondaryAvailabilityZone *string `json:"secondaryAvailabilityZone,omitempty"`
	// The VPC security group for the instance.
	// +kubebuilder:validation:Optional
	SecurityGroups []*VPCSecurityGroupMembership `json:"securityGroups,omitempty"`
	// The subnet group for the replication instance.
	// +kubebuilder:validation:Optional
	SubnetGroup *ReplicationSubnetGroup_SDK `json:"subnetGroup,omitempty"`
}

// ReplicationInstance is the Schema for the ReplicationInstances API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Synced",type="string",priority=0,JSONPath=".status.conditions[?(@.type==\"ACK.ResourceSynced\")].status"
// +kubebuilder:printcolumn:name="Age",type="date",priority=0,JSONPath=".metadata.creationTimestamp"
type ReplicationInstance struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ReplicationInstanceSpec   `json:"spec,omitempty"`
	Status            ReplicationInstanceStatus `json:"status,omitempty"`
}

// ReplicationInstanceList contains a list of ReplicationInstance
// +kubebuilder:object:root=true
type ReplicationInstanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ReplicationInstance `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ReplicationInstance{}, &ReplicationInstanceList{})
}
