// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ReplicationTaskSpec defines the desired state of ReplicationTask.
//
// Provides information that describes a replication task created by the CreateReplicationTask
// operation.
type ReplicationTaskSpec struct {

	// Indicates when you want a change data capture (CDC) operation to start. Use
	// either CdcStartPosition or CdcStartTime to specify when you want a CDC operation
	// to start. Specifying both values results in an error.
	//
	// The value can be in date, checkpoint, or LSN/SCN format.
	//
	// Date Example: --cdc-start-position “2018-03-08T12:12:12”
	//
	// Checkpoint Example: --cdc-start-position "checkpoint:V1#27#mysql-bin-changelog.157832:1975:-1:2002:677883278264080:mysql-bin-changelog.157832:1876#0#0#*#0#93"
	//
	// LSN Example: --cdc-start-position “mysql-bin-changelog.000024:373”
	//
	// When you use this task setting with a source PostgreSQL database, a logical
	// replication slot should already be created and associated with the source
	// endpoint. You can verify this by setting the slotName extra connection attribute
	// to the name of this logical replication slot. For more information, see Extra
	// Connection Attributes When Using PostgreSQL as a Source for DMS (https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.PostgreSQL.html#CHAP_Source.PostgreSQL.ConnectionAttrib).
	CdcStartPosition *string `json:"cdcStartPosition,omitempty"`
	// Indicates the start time for a change data capture (CDC) operation. Use either
	// CdcStartTime or CdcStartPosition to specify when you want a CDC operation
	// to start. Specifying both values results in an error.
	//
	// Timestamp Example: --cdc-start-time “2018-03-08T12:12:12”
	CdcStartTime *metav1.Time `json:"cdcStartTime,omitempty"`
	// Indicates when you want a change data capture (CDC) operation to stop. The
	// value can be either server time or commit time.
	//
	// Server time example: --cdc-stop-position “server_time:2018-02-09T12:12:12”
	//
	// Commit time example: --cdc-stop-position “commit_time:2018-02-09T12:12:12“
	CdcStopPosition *string `json:"cdcStopPosition,omitempty"`
	// The migration type. Valid values: full-load | cdc | full-load-and-cdc
	// +kubebuilder:validation:Required
	MigrationType *string `json:"migrationType"`
	// An identifier for the replication task.
	//
	// Constraints:
	//
	//   - Must contain 1-255 alphanumeric characters or hyphens.
	//
	//   - First character must be a letter.
	//
	//   - Cannot end with a hyphen or contain two consecutive hyphens.
	//
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The Amazon Resource Name (ARN) of a replication instance.
	// +kubebuilder:validation:Required
	ReplicationInstanceARN *string `json:"replicationInstanceARN"`
	// Overall settings for the task, in JSON format. For more information, see
	// Specifying Task Settings for Database Migration Service Tasks (https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Tasks.CustomizingTasks.TaskSettings.html)
	// in the Database Migration Service User Guide.
	ReplicationTaskSettings *string `json:"replicationTaskSettings,omitempty"`
	// A friendly name for the resource identifier at the end of the EndpointArn
	// response parameter that is returned in the created Endpoint object. The value
	// for this parameter can have up to 31 characters. It can contain only ASCII
	// letters, digits, and hyphen ('-'). Also, it can't end with a hyphen or contain
	// two consecutive hyphens, and can only begin with a letter, such as Example-App-ARN1.
	// For example, this value might result in the EndpointArn value arn:aws:dms:eu-west-1:012345678901:rep:Example-App-ARN1.
	// If you don't specify a ResourceIdentifier value, DMS generates a default
	// identifier value for the end of EndpointArn.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	ResourceIdentifier *string `json:"resourceIdentifier,omitempty"`
	// An Amazon Resource Name (ARN) that uniquely identifies the source endpoint.
	SourceEndpointARN    *string                                  `json:"sourceEndpointARN,omitempty"`
	SourceEndpointRef    *ackv1alpha1.AWSResourceReferenceWrapper `json:"sourceEndpointRef,omitempty"`
	StartReplicationTask *string                                  `json:"startReplicationTask,omitempty"`
	// The table mappings for the task, in JSON format. For more information, see
	// Using Table Mapping to Specify Task Settings (https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Tasks.CustomizingTasks.TableMapping.html)
	// in the Database Migration Service User Guide.
	// +kubebuilder:validation:Required
	TableMappings *string `json:"tableMappings"`
	// One or more tags to be assigned to the replication task.
	Tags []*Tag `json:"tags,omitempty"`
	// An Amazon Resource Name (ARN) that uniquely identifies the target endpoint.
	TargetEndpointARN *string                                  `json:"targetEndpointARN,omitempty"`
	TargetEndpointRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"targetEndpointRef,omitempty"`
	// Supplemental information that the task requires to migrate the data for certain
	// source and target endpoints. For more information, see Specifying Supplemental
	// Data for Task Settings (https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Tasks.TaskData.html)
	// in the Database Migration Service User Guide.
	TaskData *string `json:"taskData,omitempty"`
}

// ReplicationTaskStatus defines the observed state of ReplicationTask
type ReplicationTaskStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The last error (failure) message generated for the replication task.
	// +kubebuilder:validation:Optional
	LastFailureMessage *string `json:"lastFailureMessage,omitempty"`
	// Indicates the last checkpoint that occurred during a change data capture
	// (CDC) operation. You can provide this value to the CdcStartPosition parameter
	// to start a CDC operation that begins at that checkpoint.
	// +kubebuilder:validation:Optional
	RecoveryCheckpoint *string `json:"recoveryCheckpoint,omitempty"`
	// The date the replication task was created.
	// +kubebuilder:validation:Optional
	ReplicationTaskCreationDate *metav1.Time `json:"replicationTaskCreationDate,omitempty"`
	// The date the replication task is scheduled to start.
	// +kubebuilder:validation:Optional
	ReplicationTaskStartDate *metav1.Time `json:"replicationTaskStartDate,omitempty"`
	// The statistics for the task, including elapsed time, tables loaded, and table
	// errors.
	// +kubebuilder:validation:Optional
	ReplicationTaskStats *ReplicationTaskStats `json:"replicationTaskStats,omitempty"`
	// The reason the replication task was stopped. This response parameter can
	// return one of the following values:
	//
	//    * "Stop Reason NORMAL" – The task completed successfully with no additional
	//    information returned.
	//
	//    * "Stop Reason RECOVERABLE_ERROR"
	//
	//    * "Stop Reason FATAL_ERROR"
	//
	//    * "Stop Reason FULL_LOAD_ONLY_FINISHED" – The task completed the full
	//    load phase. DMS applied cached changes if you set StopTaskCachedChangesApplied
	//    to true.
	//
	//    * "Stop Reason STOPPED_AFTER_FULL_LOAD" – Full load completed, with
	//    cached changes not applied
	//
	//    * "Stop Reason STOPPED_AFTER_CACHED_EVENTS" – Full load completed, with
	//    cached changes applied
	//
	//    * "Stop Reason EXPRESS_LICENSE_LIMITS_REACHED"
	//
	//    * "Stop Reason STOPPED_AFTER_DDL_APPLY" – User-defined stop task after
	//    DDL applied
	//
	//    * "Stop Reason STOPPED_DUE_TO_LOW_MEMORY"
	//
	//    * "Stop Reason STOPPED_DUE_TO_LOW_DISK"
	//
	//    * "Stop Reason STOPPED_AT_SERVER_TIME" – User-defined server time for
	//    stopping task
	//
	//    * "Stop Reason STOPPED_AT_COMMIT_TIME" – User-defined commit time for
	//    stopping task
	//
	//    * "Stop Reason RECONFIGURATION_RESTART"
	//
	//    * "Stop Reason RECYCLE_TASK"
	// +kubebuilder:validation:Optional
	StopReason *string `json:"stopReason,omitempty"`
	// The ARN of the replication instance to which this task is moved in response
	// to running the MoveReplicationTask (https://docs.aws.amazon.com/dms/latest/APIReference/API_MoveReplicationTask.html)
	// operation. Otherwise, this response parameter isn't a member of the ReplicationTask
	// object.
	// +kubebuilder:validation:Optional
	TargetReplicationInstanceARN *string `json:"targetReplicationInstanceARN,omitempty"`
	// The status of the replication task. This response parameter can return one
	// of the following values:
	//
	//    * "moving" – The task is being moved in response to running the MoveReplicationTask
	//    (https://docs.aws.amazon.com/dms/latest/APIReference/API_MoveReplicationTask.html)
	//    operation.
	//
	//    * "creating" – The task is being created in response to running the
	//    CreateReplicationTask (https://docs.aws.amazon.com/dms/latest/APIReference/API_CreateReplicationTask.html)
	//    operation.
	//
	//    * "deleting" – The task is being deleted in response to running the
	//    DeleteReplicationTask (https://docs.aws.amazon.com/dms/latest/APIReference/API_DeleteReplicationTask.html)
	//    operation.
	//
	//    * "failed" – The task failed to successfully complete the database migration
	//    in response to running the StartReplicationTask (https://docs.aws.amazon.com/dms/latest/APIReference/API_StartReplicationTask.html)
	//    operation.
	//
	//    * "failed-move" – The task failed to move in response to running the
	//    MoveReplicationTask (https://docs.aws.amazon.com/dms/latest/APIReference/API_MoveReplicationTask.html)
	//    operation.
	//
	//    * "modifying" – The task definition is being modified in response to
	//    running the ModifyReplicationTask (https://docs.aws.amazon.com/dms/latest/APIReference/API_ModifyReplicationTask.html)
	//    operation.
	//
	//    * "ready" – The task is in a ready state where it can respond to other
	//    task operations, such as StartReplicationTask (https://docs.aws.amazon.com/dms/latest/APIReference/API_StartReplicationTask.html)
	//    or DeleteReplicationTask (https://docs.aws.amazon.com/dms/latest/APIReference/API_DeleteReplicationTask.html).
	//
	//    * "running" – The task is performing a database migration in response
	//    to running the StartReplicationTask (https://docs.aws.amazon.com/dms/latest/APIReference/API_StartReplicationTask.html)
	//    operation.
	//
	//    * "starting" – The task is preparing to perform a database migration
	//    in response to running the StartReplicationTask (https://docs.aws.amazon.com/dms/latest/APIReference/API_StartReplicationTask.html)
	//    operation.
	//
	//    * "stopped" – The task has stopped in response to running the StopReplicationTask
	//    (https://docs.aws.amazon.com/dms/latest/APIReference/API_StopReplicationTask.html)
	//    operation.
	//
	//    * "stopping" – The task is preparing to stop in response to running
	//    the StopReplicationTask (https://docs.aws.amazon.com/dms/latest/APIReference/API_StopReplicationTask.html)
	//    operation.
	//
	//    * "testing" – The database migration specified for this task is being
	//    tested in response to running either the StartReplicationTaskAssessmentRun
	//    (https://docs.aws.amazon.com/dms/latest/APIReference/API_StartReplicationTaskAssessmentRun.html)
	//    or the StartReplicationTaskAssessment (https://docs.aws.amazon.com/dms/latest/APIReference/API_StartReplicationTaskAssessment.html)
	//    operation. StartReplicationTaskAssessmentRun (https://docs.aws.amazon.com/dms/latest/APIReference/API_StartReplicationTaskAssessmentRun.html)
	//    is an improved premigration task assessment operation. The StartReplicationTaskAssessment
	//    (https://docs.aws.amazon.com/dms/latest/APIReference/API_StartReplicationTaskAssessment.html)
	//    operation assesses data type compatibility only between the source and
	//    target database of a given migration task. In contrast, StartReplicationTaskAssessmentRun
	//    (https://docs.aws.amazon.com/dms/latest/APIReference/API_StartReplicationTaskAssessmentRun.html)
	//    enables you to specify a variety of premigration task assessments in addition
	//    to data type compatibility. These assessments include ones for the validity
	//    of primary key definitions and likely issues with database migration performance,
	//    among others.
	// +kubebuilder:validation:Optional
	TaskStatus *string `json:"taskStatus,omitempty"`
}

// ReplicationTask is the Schema for the ReplicationTasks API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type ReplicationTask struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ReplicationTaskSpec   `json:"spec,omitempty"`
	Status            ReplicationTaskStatus `json:"status,omitempty"`
}

// ReplicationTaskList contains a list of ReplicationTask
// +kubebuilder:object:root=true
type ReplicationTaskList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ReplicationTask `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ReplicationTask{}, &ReplicationTaskList{})
}
